-- Tarjetas Shell Clubsmart que hayan acumulado puntos un día  ");
-- y en ese mismo día hayan canjeado cualquiera de los regalos de la tabla de abajo ");
 ");
query.append("select convert(nvarchar,dateadd([day],-1,getdate()),112) as fecha, sq1.cl_tarjeta, totalCanjes,  ");
query.append("tcf48.darti as regalo, tcf49.CL_REGALO, sum(abs(tcf49.unidades)) as unidades, sum(abs(tcf49.puntos)) as puntos ");
query.append("from ( ");
query.append("select CL_TARJETA,  ");
query.append("( ");
query.append("	SELECT count(*)  ");
query.append("	from tcf14fi     ");
query.append("	inner join tcf49 ON tcf14fi.FECHA = tcf49.FECHA_MOV AND tcf14fi.N_VENTA = tcf49.N_VENTA  ");
query.append("	AND tcf14fi.C_VENTA = tcf49.CL_CENTRO   ");
query.append("	AND tcf14fi.CL_EMPRESA = tcf49.CL_EMPRESA AND tcf14fi.P_VENTA = tcf49.CL_TPV   ");
query.append("	where tcf14fi.T_OPERACION='C'  ");
query.append("	and tcf14fi.E_OPERACION = 'R' and tcf14fi.C_RESULTADO='000'   ");
query.append("	and tcf14fi.cl_Tarjeta = trx.cl_tarjeta  ");
query.append("	and tcf14fi.fecha = convert(nvarchar,dateadd([day],-1,getdate()),112)  ");
query.append("	and cl_regalo in ( select cl_regalo collate Latin1_General_CI_AI from zzz_angrybirds_promo_regalos )  ");
query.append(") as totalCanjes   ");
query.append("from tcf14fi as trx where E_OPERACION = 'R' and C_RESULTADO='000'      ");
query.append("and T_OPERACION = 'M'  ");
query.append("and trx.fecha = convert(nvarchar,dateadd([day],-1,getdate()),112)  ");
query.append("and (LEFT(CL_TARJETA, 6) = '700421')  ");
query.append(") as sq1  ");
query.append("inner join tcf14fi on tcf14fi.CL_TARJETA = sq1.cl_tarjeta  ");
query.append("inner join tcf49 ON tcf14fi.FECHA = tcf49.FECHA_MOV AND tcf14fi.N_VENTA = tcf49.N_VENTA   ");
query.append("		AND tcf14fi.C_VENTA = tcf49.CL_CENTRO   ");
query.append("		AND tcf14fi.CL_EMPRESA = tcf49.CL_EMPRESA AND tcf14fi.P_VENTA = tcf49.CL_TPV   ");
query.append("		and tcf49.cl_regalo in ( select cl_regalo collate Latin1_General_CI_AI from zzz_angrybirds_promo_regalos )  ");
query.append("inner join tcf48 on tcf48.cl_arti = tcf49.CL_REGALO   ");
query.append("where totalCanjes > 0    ");
query.append("group by sq1.cl_tarjeta, sq1.totalCanjes, tcf49.CL_REGALO, tcf48.darti   ");
 ");
 ");
-- Tarjetas Shell Clubsmart que hayan canjeado cualquier artículo de la tabla de abajo  ");
-- y no tengan operaciones de acumulación en ese mismo. ");
query.append("select convert(nvarchar,dateadd([day],-1,getdate()),112) as fecha, sq1.cl_tarjeta, totalAcum  ");
query.append(",tcf48.darti as regalo, tcf49.CL_REGALO, sum(abs(tcf49.unidades)) as unidades, sum(abs(tcf49.puntos)) as puntos ");
query.append("from ( ");
query.append("SELECT CL_TARJETA, ");
query.append("(	 ");
query.append("	select count(*) from tcf14fi where tcf14fi.E_OPERACION = 'R' and tcf14fi.C_RESULTADO='000'      ");
query.append("and tcf14fi.T_OPERACION = 'M'  and tcf14fi.fecha = convert(nvarchar,dateadd([day],-1,getdate()),112) ");
query.append("and tcf14fi.CL_TARJETA = trx.CL_TARJETA ");
query.append(") as totalAcum ");
query.append("from tcf14fi AS trx    ");
query.append("inner join tcf49 ON trx.FECHA = tcf49.FECHA_MOV AND trx.N_VENTA = tcf49.N_VENTA AND trx.C_VENTA = tcf49.CL_CENTRO AND  ");
query.append("		   trx.CL_EMPRESA = tcf49.CL_EMPRESA AND trx.P_VENTA = tcf49.CL_TPV   ");
query.append("where T_OPERACION='C'  ");
query.append("and (LEFT(trx.CL_TARJETA, 6) = '700421')  ");
query.append("and trx.E_OPERACION = 'R' and trx.C_RESULTADO='000'   ");
query.append("and trx.fecha = convert(nvarchar,dateadd([day],-1,getdate()),112) ");
query.append("and cl_regalo in ( select cl_regalo collate Latin1_General_CI_AI from zzz_angrybirds_promo_regalos ) ");
query.append(") as sq1 ");
query.append("inner join tcf14fi on tcf14fi.CL_TARJETA = sq1.cl_tarjeta  ");
query.append("inner join tcf49 ON tcf14fi.FECHA = tcf49.FECHA_MOV AND tcf14fi.N_VENTA = tcf49.N_VENTA   ");
query.append("		AND tcf14fi.C_VENTA = tcf49.CL_CENTRO   ");
query.append("		AND tcf14fi.CL_EMPRESA = tcf49.CL_EMPRESA AND tcf14fi.P_VENTA = tcf49.CL_TPV   ");
query.append("		and tcf49.cl_regalo in ( select cl_regalo collate Latin1_General_CI_AI from zzz_angrybirds_promo_regalos )  ");
query.append("inner join tcf48 on tcf48.cl_arti = tcf49.CL_REGALO   ");
query.append("where totalAcum = 0 ");
query.append("group by sq1.cl_tarjeta, sq1.totalAcum, tcf49.CL_REGALO, tcf48.darti   ");