/* Regularizaciones Fidelización */

SELECT     TCF93.CL_CLIENTE, TCF93.CL_TARJETA, TCF93.CL_CENTRO, EstacionesClubSmart_ACTIVAS.DESCRIPCION AS NOMBRE_ESTACION, TCF40.NOMBRE, 
TCF40.APELLIDO1, TCF40.APELLIDO2, TCF40.DOCID, TCF93.MOTIVO, TCF93.OBSERVACIONES, SUM(TCF93.PUNTOS) AS PUNTOS 
, (select top 1 CL_CENTRO from EstacionesClubSmart_ACTIVAS where EstacionesClubSmart_ACTIVAS.cl_empresa = TCF40.CL_EMPRESA_HAB and EstacionesClubSmart_ACTIVAS.cl_centro = tcf40.CL_CENTRO_HAB) as centroEstacionAsignada
, (select top 1 descripcion from EstacionesClubSmart_ACTIVAS where EstacionesClubSmart_ACTIVAS.cl_empresa = TCF40.CL_EMPRESA_HAB and EstacionesClubSmart_ACTIVAS.cl_centro = tcf40.CL_CENTRO_HAB) as nombreEstacionAsignada

FROM         TCF93 INNER JOIN 
TCF40 ON TCF93.CL_CLIENTE = TCF40.CL_CLIENTE LEFT OUTER JOIN 
EstacionesClubSmart_ACTIVAS ON TCF93.CL_CENTRO = EstacionesClubSmart_ACTIVAS.CL_CENTRO 
WHERE  (TCF93.TIPO_MOV IN ('R','T','A')) 
AND (TCF93.FECHA >= '20160401') 
AND (TCF93.FECHA <= '20160430') 
and (left(tcf93.cl_tarjeta,6)= '972400')
GROUP BY TCF93.CL_CLIENTE, TCF93.CL_TARJETA, TCF93.CL_CENTRO, TCF40.NOMBRE, TCF40.APELLIDO1, TCF40.APELLIDO2, TCF40.DOCID, TCF93.MOTIVO, TCF93.OBSERVACIONES, 
EstacionesClubSmart_ACTIVAS.DESCRIPCION , tcf40.CL_EMPRESA_HAB, tcf40.CL_CENTRO_HAB
HAVING     (TCF93.MOTIVO NOT LIKE 'Incentivo%') 
ORDER BY TCF93.CL_CLIENTE 