/* TRX. EESS (Detalle) */

SELECT     EstacionesClubSmart_ACTIVAS.DESCRIPCION, EstacionesClubSmart_ACTIVAS.COD_ESTABL, 
CF_DISA_HIST.dbo.TCF16FI_H.FECHA, CF_DISA_HIST.dbo.TCF16FI_H.HORA, CF_DISA_HIST.dbo.TCF16FI_H.N_REFERENCIA AS TICKET, 
CF_DISA_HIST.dbo.TCF16FI_H.CL_TARJETA, TCF40.NOMBRE, TCF40.APELLIDO1, TCF40.APELLIDO2,  
SUM(CF_DISA_HIST.dbo.TCF67_H.PUNTOS) AS PUNTOS, 
CF_DISA_HIST.dbo.TCF67_H.CL_ARTI, TCF48.DARTI, 
CF_DISA_HIST.dbo.TCF67_H.UNIDADES 
FROM         CF_DISA_HIST.dbo.TCF67_H 
LEFT OUTER JOIN TCF48 ON CF_DISA_HIST.dbo.TCF67_H.CL_ARTI = TCF48.CL_ARTI 
INNER JOIN CF_DISA_HIST.dbo.TCF16FI_H 
INNER JOIN TCF40 ON CF_DISA_HIST.dbo.TCF16FI_H.CL_CLIENTE = TCF40.CL_CLIENTE 
INNER JOIN TCF41 ON CF_DISA_HIST.dbo.TCF16FI_H.CL_TARJETA = TCF41.CL_TARJETA 
INNER JOIN EstacionesClubSmart_ACTIVAS ON CF_DISA_HIST.dbo.TCF16FI_H.C_VENTA = 
EstacionesClubSmart_ACTIVAS.CL_CENTRO ON CF_DISA_HIST.dbo.TCF67_H.FECHA = CF_DISA_HIST.dbo.TCF16FI_H.FECHA 
AND  CF_DISA_HIST.dbo.TCF67_H.CL_EMPRESA = CF_DISA_HIST.dbo.TCF16FI_H.CL_EMPRESA 
AND CF_DISA_HIST.dbo.TCF67_H.CL_CENTRO = CF_DISA_HIST.dbo.TCF16FI_H.C_VENTA 
AND CF_DISA_HIST.dbo.TCF67_H.CL_TPV = CF_DISA_HIST.dbo.TCF16FI_H.P_VENTA 
AND  CF_DISA_HIST.dbo.TCF67_H.N_VENTA = CF_DISA_HIST.dbo.TCF16FI_H.N_VENTA 
WHERE       (CF_DISA_HIST.dbo.TCF16FI_H.T_OPERACION = 'M') 
AND (CF_DISA_HIST.dbo.TCF16FI_H.FECHA >= '20160316') 
AND (CF_DISA_HIST.dbo.TCF16FI_H.FECHA <= '20160316')   
AND (CF_DISA_HIST.dbo.TCF16FI_H.C_VENTA = '2026')   
AND (CF_DISA_HIST.dbo.TCF16FI_H.SALDO_POST - CF_DISA_HIST.dbo.TCF16FI_H.SALDO_PREV > 0)  
and CF_DISA_HIST.dbo.TCF16FI_H.CL_TARJETA ='70042107107272110'
GROUP BY EstacionesClubSmart_ACTIVAS.DESCRIPCION, EstacionesClubSmart_ACTIVAS.COD_ESTABL, 
CF_DISA_HIST.dbo.TCF16FI_H.FECHA, CF_DISA_HIST.dbo.TCF16FI_H.HORA, CF_DISA_HIST.dbo.TCF16FI_H.N_REFERENCIA,
CF_DISA_HIST.dbo.TCF16FI_H.CL_TARJETA, TCF40.NOMBRE, TCF40.APELLIDO1, TCF40.APELLIDO2,  
CF_DISA_HIST.dbo.TCF67_H.CL_ARTI, TCF48.DARTI, 
CF_DISA_HIST.dbo.TCF67_H.UNIDADES 
ORDER BY CF_DISA_HIST.dbo.TCF16FI_H.FECHA, CF_DISA_HIST.dbo.TCF16FI_H.HORA  