SELECT TCF11.CL_CA AS CL_CA,       
		       TCF14FI.CL_CLIENTE AS CL_CLIENTE,   
		       TCF14FI.ID_CUENTA AS ID_CUENTA,    
		       TCF14FI.N_VENTA AS N_VENTA,   
		       TCF14FI.FECHA AS FECHA,   
		       TCF14FI.HORA AS HORA,   
		       TCF14FI.CL_TARJETA AS CL_TARJETA,   
		       TCF11.COD_ESTABL AS COD_ESTABL,   
		       TCF04.DESCRIPCION AS ESTACION,    
		       TCF42.SALDO_PUNTOS AS SALDO_PUNTOS,   
		       TCF14FI.CL_CAMPA AS CL_CAMPA,   
		       TCF14FI.P_VENTA AS P_VENTA,    
		       TCF14FI.C_VENTA AS C_VENTA,   
		       TCF14FI.CL_EMPRESA AS CL_EMPRESA,   
		       CAST(TCF67.UNIDADES AS MONEY) AS UNIDADES,   
		       TCF48.DARTI AS ArticuloM,   
		       TCF48_1.DARTI AS ArticuloC,   
		       TCF14FI.T_OPERACION AS T_OPERACION,   
		       TCF67.IMPORTE AS IMPORTE,   
		       sum(TCF67.PUNTOS) AS PUNTOSM,   
		       TCF14FI.SALDO_PREV AS SALDO_PREV,   
		       TCF14FI.SALDO_POST AS SALDO_POST,   
		       TCF49.PUNTOS AS PUNTOSC,   
		       CAST(ABS(TCF49.UNIDADES) AS MONEY) AS UNIDADESCANJE,   
		       TCF48.CL_ARTI AS CODPRODUCTO,   
		       TCF48_1.CL_ARTI AS CODREGALO    
		FROM TCF49 INNER JOIN   
		     TCF48 TCF48_1 ON TCF49.CL_REGALO = TCF48_1.CL_ARTI RIGHT OUTER JOIN   
		     TCF14FI INNER JOIN   
		     TCF11 ON TCF14FI.CL_EMPRESA = TCF11.CL_EMPRESA AND TCF14FI.C_VENTA = TCF11.CL_CENTRO INNER JOIN   
		//     TCF42 ON TCF14FI.ID_CUENTA = TCF42.ID_CUENTA INNER JOIN   
		     TCF04 ON TCF14FI.CL_EMPRESA = TCF04.CL_EMPRESA AND TCF14FI.C_VENTA = TCF04.CL_CENTRO ON    
		     TCF49.FECHA_MOV = TCF14FI.FECHA AND TCF49.HORA_MOV = TCF14FI.HORA AND   
		     TCF49.CL_EMPRESA = TCF14FI.CL_EMPRESA AND TCF49.CL_CENTRO = TCF14FI.C_VENTA AND    
		     TCF49.N_VENTA = TCF14FI.N_VENTA AND TCF49.CL_TPV = TCF14FI.P_VENTA AND    
		     TCF49.CL_CAMPA = TCF14FI.CL_CAMPA LEFT OUTER JOIN   
		     TCF48 INNER JOIN   
		     TCF67 ON TCF48.CL_ARTI = TCF67.CL_ARTI ON TCF14FI.N_VENTA = TCF67.N_VENTA AND    
		     TCF14FI.CL_CAMPA = TCF67.CL_CAMPA AND TCF14FI.P_VENTA = TCF67.CL_TPV AND    
		     TCF14FI.C_VENTA = TCF67.CL_CENTRO AND TCF14FI.CL_EMPRESA = TCF67.CL_EMPRESA AND    
		     TCF14FI.FECHA = TCF67.FECHA   
		//   nuevo
		     inner join dbo.TCF41 ON dbo.TCF14FI.CL_TARJETA = dbo.TCF41.CL_TARJETA 
		     inner join dbo.TCF40 ON dbo.TCF41.CL_CLIENTE = dbo.TCF40.CL_CLIENTE  
		     inner join dbo.TCF42 ON dbo.TCF41.ID_CUENTA = dbo.TCF42.ID_CUENTA  
		 //  fin
		WHERE 
		query.append(filtrarEstacionesUsuario("TCF14FI",request));
		      (TCF11.CL_CA = '000001')   
		      AND TCF14FI.C_RESULTADO = '000'   
    	      AND (TCF14FI.CL_CLIENTE = '"+clCliente+"') 
		      AND (TCF14FI.fecha >= '"+DisaUtils.parseDateForCF(DateUtils.addMonths(new Date(), -4))+"') 
		      AND (TCF14FI.T_OPERACION IN ('M','A'))  
		GROUP BY 
		    TCF11.CL_CA,       
		    TCF14FI.CL_CLIENTE,     
		    TCF14FI.ID_CUENTA,      
		    TCF14FI.N_VENTA,     
		    TCF14FI.FECHA,     
		    TCF14FI.HORA,     
		    TCF14FI.CL_TARJETA,     
		    TCF11.COD_ESTABL,     
		    TCF04.DESCRIPCION,      
		    TCF42.SALDO_PUNTOS,     
		    TCF14FI.CL_CAMPA,     
		    TCF14FI.P_VENTA,      
		    TCF14FI.C_VENTA,     
		    TCF14FI.CL_EMPRESA,     
		    TCF67.UNIDADES,     
		    TCF48.DARTI,     
		    TCF48_1.DARTI,     
		    TCF14FI.T_OPERACION,     
		    TCF67.IMPORTE,     
		    TCF14FI.SALDO_PREV,     
		    TCF14FI.SALDO_POST,     
		    TCF49.PUNTOS,     
		    TCF49.UNIDADES,     
		    TCF48.CL_ARTI,     
		    TCF48_1.CL_ARTI      
		UNION  
		SELECT TCF11.CL_CA AS CL_CA,         
		       TCF14FI.CL_CLIENTE AS CL_CLIENTE,   
		       TCF14FI.ID_CUENTA AS ID_CUENTA,    
		       TCF14FI.N_VENTA AS N_VENTA,   
		       TCF14FI.FECHA AS FECHA,   
		       TCF14FI.HORA AS HORA,   
		       TCF14FI.CL_TARJETA AS CL_TARJETA,   
		       TCF11.COD_ESTABL AS COD_ESTABL,   
		       TCF04.DESCRIPCION AS ESTACION,    
		       TCF42.SALDO_PUNTOS AS SALDO_PUNTOS,   
		       TCF14FI.CL_CAMPA AS CL_CAMPA,   
		       TCF14FI.P_VENTA AS P_VENTA,    
		       TCF14FI.C_VENTA AS C_VENTA,   
		       TCF14FI.CL_EMPRESA AS CL_EMPRESA,   
		       CAST(TCF49.UNIDADES AS MONEY) AS UNIDADES,   
		       '' AS ArticuloM,   
		       TCF48.DARTI AS ArticuloC,   
		       TCF14FI.T_OPERACION AS T_OPERACION,   
		       0 AS IMPORTE,   
		       0 AS PUNTOSM,   
		       TCF14FI.SALDO_PREV AS SALDO_PREV,   
		       TCF14FI.SALDO_POST AS SALDO_POST,   
		       TCF49.PUNTOS AS PUNTOSC,   
		       CAST(ABS(TCF49.UNIDADES) AS MONEY) AS UNIDADESCANJE,   
		       '' AS CODPRODUCTO,   
		       TCF49.CL_REGALO AS CODREGALO    
		FROM TCF14FI INNER JOIN  
		     TCF49 ON TCF49.FECHA_MOV = TCF14FI.FECHA AND TCF49.HORA_MOV = TCF14FI.HORA AND   
		     TCF49.CL_EMPRESA = TCF14FI.CL_EMPRESA AND TCF49.CL_CENTRO = TCF14FI.C_VENTA AND    
		     TCF49.N_VENTA = TCF14FI.N_VENTA AND TCF49.CL_TPV = TCF14FI.P_VENTA     
		     INNER JOIN TCF48 ON TCF49.CL_REGALO = TCF48.CL_ARTI  
		     INNER JOIN TCF11 ON TCF14FI.CL_EMPRESA = TCF11.CL_EMPRESA AND TCF14FI.C_VENTA = TCF11.CL_CENTRO   
		     INNER JOIN TCF42 ON TCF14FI.ID_CUENTA = TCF42.ID_CUENTA   
		     INNER JOIN TCF04 ON TCF14FI.CL_EMPRESA = TCF04.CL_EMPRESA AND TCF14FI.C_VENTA = TCF04.CL_CENTRO     
		WHERE 
		query.append(filtrarEstacionesUsuario("TCF14FI",request));
		      (TCF11.CL_CA = '000001')   
		      AND TCF14FI.C_RESULTADO = '000'   
              AND (TCF14FI.CL_CLIENTE = '"+clCliente+"') 
		      AND (TCF14FI.fecha >= '"+DisaUtils.parseDateForCF(DateUtils.addMonths(new Date(), -4))+"') 
		      AND (TCF14FI.T_OPERACION IN ('C','X') )  
         ORDER BY TCF14FI.FECHA DESC, TCF14FI.HORA DESC 