USE [CF_DISA]
GO
/****** Object:  View [dbo].[EstacionesChequesDisa]    Script Date: 27/04/2017 12:37:44 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[EstacionesChequesDisa]
AS
SELECT DISTINCT 
                      TOP (100) PERCENT dbo.TCF11.CL_CENTRO, dbo.TCF11.COD_ESTABL, dbo.TCF04.DESCRIPCION, dbo.TCF04.CL_EMPRESA, 
                      dbo.TCF04.DATO_ADICIONAL1 AS BANDERA, dbo.TCF30.CIF, dbo.TCF30.DESCRIPCION AS RAZON
FROM         dbo.TCF04 INNER JOIN
                      dbo.TCF11 ON dbo.TCF04.CL_EMPRESA = dbo.TCF11.CL_EMPRESA AND dbo.TCF04.CL_CENTRO = dbo.TCF11.CL_CENTRO INNER JOIN
                      dbo.TCF30 ON dbo.TCF04.CL_EMPRESA = dbo.TCF30.CL_EMPRESA
WHERE     (dbo.TCF11.CL_CA IN ('000001', '000002')) AND (dbo.TCF04.ESTADO = 1)
ORDER BY dbo.TCF04.DESCRIPCION

GO

USE [CF_DISA]
GO
/****** Object:  View [dbo].[EstacionesChequesDisaTodas]    Script Date: 27/04/2017 12:37:53 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[EstacionesChequesDisaTodas]
AS
SELECT DISTINCT 
                      TOP (100) PERCENT dbo.TCF11.CL_CENTRO, dbo.TCF11.COD_ESTABL, dbo.TCF04.DESCRIPCION, dbo.TCF04.CL_EMPRESA, 
                      dbo.TCF04.DATO_ADICIONAL1 AS BANDERA, dbo.TCF30.CIF, dbo.TCF30.DESCRIPCION AS RAZON
FROM         dbo.TCF04 INNER JOIN
                      dbo.TCF11 ON dbo.TCF04.CL_EMPRESA = dbo.TCF11.CL_EMPRESA AND dbo.TCF04.CL_CENTRO = dbo.TCF11.CL_CENTRO INNER JOIN
                      dbo.TCF30 ON dbo.TCF04.CL_EMPRESA = dbo.TCF30.CL_EMPRESA
WHERE     (dbo.TCF11.CL_CA IN ('000001', '000002'))
ORDER BY dbo.TCF04.DESCRIPCION

GO

USE [CF_DISA]
GO
/****** Object:  View [dbo].[EstacionesClubSmart]    Script Date: 27/04/2017 12:38:04 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
create VIEW [dbo].[EstacionesClubSmart]
AS
SELECT DISTINCT TOP (100) PERCENT dbo.TCF11.CL_EMPRESA, dbo.TCF11.CL_CENTRO, dbo.TCF11.COD_ESTABL, dbo.TCF04.DESCRIPCION
FROM         dbo.TCF04 INNER JOIN
                      dbo.TCF11 ON dbo.TCF04.CL_EMPRESA = dbo.TCF11.CL_EMPRESA AND dbo.TCF04.CL_CENTRO = dbo.TCF11.CL_CENTRO
WHERE     (dbo.TCF11.CL_CA = '000001')
GO

USE [CF_DISA]
GO
/****** Object:  View [dbo].[EstacionesClubSmart_ACTIVAS]    Script Date: 27/04/2017 12:38:15 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
create VIEW [dbo].[EstacionesClubSmart_ACTIVAS]
AS
SELECT DISTINCT 
                      TOP (100) PERCENT dbo.TCF11.CL_EMPRESA, dbo.TCF11.CL_CENTRO, dbo.TCF11.COD_ESTABL, dbo.TCF04.DESCRIPCION, 
                      dbo.TCF04.DATO_ADICIONAL1 AS bandera
FROM         dbo.TCF04 INNER JOIN
                      dbo.TCF11 ON dbo.TCF04.CL_EMPRESA = dbo.TCF11.CL_EMPRESA AND dbo.TCF04.CL_CENTRO = dbo.TCF11.CL_CENTRO
WHERE     (dbo.TCF11.CL_CA = '000001') AND (dbo.TCF04.ESTADO = '1')
GO

USE [CF_DISA]
GO

/****** Object:  View [dbo].[TodasTrxClubSmart_Angry]    Script Date: 27/04/2017 12:38:25 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE VIEW [dbo].[TodasTrxClubSmart_Angry]
AS
SELECT     C_VENTA, T_OPERACION, E_OPERACION, TCF14FI.FECHA, HORA, ID_CUENTA, CL_CLIENTE, CL_TARJETA, C_RESULTADO   , UNIDADES   , CL_REGCAL                
FROM         dbo.TCF14FI
INNER JOIN TCF67 ON TCF14FI.FECHA = TCF67.FECHA AND TCF14FI.N_VENTA = TCF67.N_VENTA AND TCF14FI.C_VENTA = TCF67.CL_CENTRO AND 
TCF14FI.CL_EMPRESA = TCF67.CL_EMPRESA AND TCF14FI.P_VENTA = TCF67.CL_TPV 
WHERE     (LEFT(CL_TARJETA, 6) = '700421')
and TCF14FI.fecha between '20150501' and '20170108'
and T_OPERACION='M' and C_RESULTADO='000' and E_OPERACION='R'
and CL_ARTI IN ('121','122','126','127','130','133','421','422','426','427','430','433','483')
 and CL_REGCAL NOT IN (29, 3, 817)
  and UNIDADES < 1000
UNION
SELECT     C_VENTA, T_OPERACION, E_OPERACION, CF_DISA_HIST.dbo.TCF16FI_H.FECHA, HORA, ID_CUENTA, CL_CLIENTE, CL_TARJETA, C_RESULTADO , UNIDADES, CL_REGCAL
FROM         CF_DISA_HIST.dbo.TCF16FI_H
INNER JOIN CF_DISA_HIST.dbo.TCF67_H ON CF_DISA_HIST.dbo.TCF16FI_H.FECHA = CF_DISA_HIST.dbo.TCF67_H.FECHA AND CF_DISA_HIST.dbo.TCF16FI_H.N_VENTA = CF_DISA_HIST.dbo.TCF67_H.N_VENTA 
AND CF_DISA_HIST.dbo.TCF16FI_H.C_VENTA = CF_DISA_HIST.dbo.TCF67_H.CL_CENTRO AND 
CF_DISA_HIST.dbo.TCF16FI_H.CL_EMPRESA = CF_DISA_HIST.dbo.TCF67_H.CL_EMPRESA AND CF_DISA_HIST.dbo.TCF16FI_H.P_VENTA = CF_DISA_HIST.dbo.TCF67_H.CL_TPV 
WHERE     (LEFT(CL_TARJETA, 6) = '700421')
and CF_DISA_HIST.dbo.TCF16FI_H.fecha between '20150501' and '20170108'
and T_OPERACION='M' and C_RESULTADO='000' and E_OPERACION='R'
and CL_ARTI IN ('121','122','126','127','130','133','421','422','426','427','430','433','483')
and CL_REGCAL NOT IN (29, 3, 817)
and UNIDADES < 1000

GO

USE [CF_DISA]
GO
/****** Object:  View [dbo].[TodasTrxClubSmart_Micro]    Script Date: 27/04/2017 12:38:37 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[TodasTrxClubSmart_Micro]
AS
SELECT     C_VENTA, T_OPERACION, E_OPERACION, FECHA, HORA, ID_CUENTA, CL_CLIENTE, CL_TARJETA, C_RESULTADO                      
FROM         dbo.TCF14FI
WHERE     (LEFT(CL_TARJETA, 6) = '700421')
UNION
SELECT     C_VENTA, T_OPERACION, E_OPERACION, FECHA, HORA, ID_CUENTA, CL_CLIENTE, CL_TARJETA, C_RESULTADO  
FROM         CF_DISA_HIST.dbo.TCF16FI_H
WHERE     (LEFT(CL_TARJETA, 6) = '700421')
GO

USE [CF_DISA]
GO
/****** Object:  View [dbo].[TodasTrxTCD_Angry]    Script Date: 27/04/2017 12:38:46 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[TodasTrxTCD_Angry]
AS
SELECT     C_VENTA, T_OPERACION, E_OPERACION, TCF14FI.FECHA, HORA, ID_CUENTA, CL_CLIENTE, CL_TARJETA, C_RESULTADO   , UNIDADES   , CL_REGCAL                
FROM         dbo.TCF14FI
INNER JOIN TCF67 ON TCF14FI.FECHA = TCF67.FECHA AND TCF14FI.N_VENTA = TCF67.N_VENTA AND TCF14FI.C_VENTA = TCF67.CL_CENTRO AND 
TCF14FI.CL_EMPRESA = TCF67.CL_EMPRESA AND TCF14FI.P_VENTA = TCF67.CL_TPV 
WHERE     (LEFT(CL_TARJETA, 9) = '972400077')
and TCF14FI.fecha between '20150501' and '20170108'
and T_OPERACION='M' and C_RESULTADO='000' and E_OPERACION='R'
and CL_ARTI IN ('121','122','126','127','130','133','421','422','426','427','430','433','483')
 and CL_REGCAL NOT IN (29, 3, 817)
 and UNIDADES < 1000
UNION
SELECT     C_VENTA, T_OPERACION, E_OPERACION, CF_DISA_HIST.dbo.TCF16FI_H.FECHA, HORA, ID_CUENTA, CL_CLIENTE, CL_TARJETA, C_RESULTADO , UNIDADES, CL_REGCAL
FROM         CF_DISA_HIST.dbo.TCF16FI_H
INNER JOIN CF_DISA_HIST.dbo.TCF67_H ON CF_DISA_HIST.dbo.TCF16FI_H.FECHA = CF_DISA_HIST.dbo.TCF67_H.FECHA AND CF_DISA_HIST.dbo.TCF16FI_H.N_VENTA = CF_DISA_HIST.dbo.TCF67_H.N_VENTA 
AND CF_DISA_HIST.dbo.TCF16FI_H.C_VENTA = CF_DISA_HIST.dbo.TCF67_H.CL_CENTRO AND 
CF_DISA_HIST.dbo.TCF16FI_H.CL_EMPRESA = CF_DISA_HIST.dbo.TCF67_H.CL_EMPRESA AND CF_DISA_HIST.dbo.TCF16FI_H.P_VENTA = CF_DISA_HIST.dbo.TCF67_H.CL_TPV 
WHERE     (LEFT(CL_TARJETA, 9) = '972400077')
and CF_DISA_HIST.dbo.TCF16FI_H.fecha between '20150501' and '20170108'
and T_OPERACION='M' and C_RESULTADO='000' and E_OPERACION='R'
and CL_ARTI IN ('121','122','126','127','130','133','421','422','426','427','430','433','483')
 and CL_REGCAL NOT IN (29, 3, 817)
 and UNIDADES < 1000
GO

USE [CF_DISA]
GO

/****** Object:  View [dbo].[TodasTrxTCD_SCS_Micro]    Script Date: 27/04/2017 12:38:58 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[TodasTrxTCD_SCS_Micro]
AS
SELECT     C_VENTA, T_OPERACION, E_OPERACION, FECHA, HORA, ID_CUENTA, CL_CLIENTE, CL_TARJETA, C_RESULTADO                      
FROM         dbo.TCF14FI
WHERE     (LEFT(CL_TARJETA,9) = '972400077') or LEFT(CL_TARJETA,6) = '700421'
UNION
SELECT     C_VENTA, T_OPERACION, E_OPERACION, FECHA, HORA, ID_CUENTA, CL_CLIENTE, CL_TARJETA, C_RESULTADO  
FROM         CF_DISA_HIST.dbo.TCF16FI_H
WHERE     (LEFT(CL_TARJETA,9) = '972400077') or LEFT(CL_TARJETA,6) = '700421'
GO

USE [CF_DISA]
GO
/****** Object:  View [dbo].[TodasTrxTuClubDISA_Micro]    Script Date: 27/04/2017 12:39:08 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[TodasTrxTuClubDISA_Micro]
AS
SELECT     C_VENTA, T_OPERACION, E_OPERACION, FECHA, HORA, ID_CUENTA, CL_CLIENTE, CL_TARJETA, C_RESULTADO                      
FROM         dbo.TCF14FI
WHERE     (LEFT(CL_TARJETA,9) = '972400077')
UNION
SELECT     C_VENTA, T_OPERACION, E_OPERACION, FECHA, HORA, ID_CUENTA, CL_CLIENTE, CL_TARJETA, C_RESULTADO  
FROM         CF_DISA_HIST.dbo.TCF16FI_H
WHERE     (LEFT(CL_TARJETA,9) = '972400077')
GO

USE [CF_DISA]
GO
/****** Object:  View [dbo].[TodosCanjesClubSmart]    Script Date: 27/04/2017 12:39:17 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[TodosCanjesClubSmart]
AS
SELECT     CL_EMPRESA, C_VENTA, P_VENTA, N_VENTA, CL_OPERADOR, T_OPERACION, T_AUTORIZACION, E_OPERACION, FECHA, HORA, T_SOPORTE, 
                      F_CAPTURA, ID_CUENTA, CL_CLIENTE, CL_TARJETA, MEDIO_PAGO, IMPORTE, MONEDA, CL_EMPRESA_DOC, CL_DOCUMENTO, C_RESULTADO, 
                      NUM_AUT, N_REFERENCIA, FECH_CAD, CL_CA, TIEMPO_RESPUESTA, COD_RES_CA, C_VENTA_ORI, P_VENTA_ORI, N_VENTA_ORI, FECHA_ORI, 
                      N_REF_CLI, SALDO_PREV, SALDO_POST, CL_CAMPA, CL_CAMPA_EXT, ACTIV_TARJETA, CUMPLE_CLIENTE, MOTIVO_ANUL, BVENIDA_CLIENTE, 
                      PARTIC_CLIENTE, CL_SORTEO
FROM         dbo.TCF14FI
WHERE     (T_OPERACION = 'C') AND (LEFT(CL_TARJETA, 6) = '700421')
UNION
SELECT     CL_EMPRESA, C_VENTA, P_VENTA, N_VENTA, CL_OPERADOR, T_OPERACION, T_AUTORIZACION, E_OPERACION, FECHA, HORA, T_SOPORTE, 
                      F_CAPTURA, ID_CUENTA, CL_CLIENTE, CL_TARJETA, MEDIO_PAGO, IMPORTE, MONEDA, CL_EMPRESA_DOC, CL_DOCUMENTO, C_RESULTADO, 
                      NUM_AUT, N_REFERENCIA, FECH_CAD, CL_CA, TIEMPO_RESPUESTA, COD_RES_CA, C_VENTA_ORI, P_VENTA_ORI, N_VENTA_ORI, FECHA_ORI, 
                      N_REF_CLI, SALDO_PREV, SALDO_POST, CL_CAMPA, CL_CAMPA_EXT, ACTIV_TARJETA, CUMPLE_CLIENTE, MOTIVO_ANUL, BVENIDA_CLIENTE, 
                      PARTIC_CLIENTE, CL_SORTEO
FROM         CF_DISA_HIST.dbo.TCF16FI_H
WHERE     (T_OPERACION = 'C') AND (LEFT(CL_TARJETA, 6) = '700421')
GO

USE [CF_DISA]
GO

/****** Object:  View [dbo].[TodosCanjesClubSmart_REPLICA]    Script Date: 27/04/2017 12:39:30 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[TodosCanjesClubSmart_REPLICA] with schemabinding
AS
SELECT     ID_CUENTA, COUNT_BIG(*) as countbig
FROM         dbo.TCF14FI
WHERE     (T_OPERACION = 'C') AND (LEFT(CL_TARJETA, 6) = '700421')
group by ID_CUENTA
GO

USE [CF_DISA]
GO
/****** Object:  View [dbo].[TodosCanjesClubSmart_SIMPLE]    Script Date: 27/04/2017 12:39:38 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[TodosCanjesClubSmart_SIMPLE]
AS
SELECT     ID_CUENTA, CL_CLIENTE
FROM         dbo.TCF14FI
WHERE     (T_OPERACION = 'C') AND (LEFT(CL_TARJETA, 6) = '700421')
UNION
SELECT     ID_CUENTA, CL_CLIENTE
FROM         CF_DISA_HIST.dbo.TCF16FI_H
WHERE     (T_OPERACION = 'C') AND (LEFT(CL_TARJETA, 6) = '700421')
GO

USE [CF_DISA]
GO
/****** Object:  View [dbo].[TodosCanjesPT]    Script Date: 27/04/2017 12:39:51 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[TodosCanjesPT]
AS
SELECT     CL_EMPRESA, C_VENTA, P_VENTA, N_VENTA, CL_OPERADOR, T_OPERACION, T_AUTORIZACION, E_OPERACION, FECHA, HORA, T_SOPORTE, 
                      F_CAPTURA, ID_CUENTA, CL_CLIENTE, CL_TARJETA, MEDIO_PAGO, IMPORTE, MONEDA, CL_EMPRESA_DOC, CL_DOCUMENTO, C_RESULTADO, 
                      NUM_AUT, N_REFERENCIA, FECH_CAD, CL_CA, TIEMPO_RESPUESTA, COD_RES_CA, C_VENTA_ORI, P_VENTA_ORI, N_VENTA_ORI, FECHA_ORI, 
                      N_REF_CLI, SALDO_PREV, SALDO_POST, CL_CAMPA, CL_CAMPA_EXT, ACTIV_TARJETA, CUMPLE_CLIENTE, MOTIVO_ANUL, BVENIDA_CLIENTE, 
                      PARTIC_CLIENTE, CL_SORTEO
FROM         dbo.TCF14FI
WHERE     (T_OPERACION = 'C') AND (LEFT(CL_TARJETA, 6) = '700428')
UNION
SELECT     CL_EMPRESA, C_VENTA, P_VENTA, N_VENTA, CL_OPERADOR, T_OPERACION, T_AUTORIZACION, E_OPERACION, FECHA, HORA, T_SOPORTE, 
                      F_CAPTURA, ID_CUENTA, CL_CLIENTE, CL_TARJETA, MEDIO_PAGO, IMPORTE, MONEDA, CL_EMPRESA_DOC, CL_DOCUMENTO, C_RESULTADO, 
                      NUM_AUT, N_REFERENCIA, FECH_CAD, CL_CA, TIEMPO_RESPUESTA, COD_RES_CA, C_VENTA_ORI, P_VENTA_ORI, N_VENTA_ORI, FECHA_ORI, 
                      N_REF_CLI, SALDO_PREV, SALDO_POST, CL_CAMPA, CL_CAMPA_EXT, ACTIV_TARJETA, CUMPLE_CLIENTE, MOTIVO_ANUL, BVENIDA_CLIENTE, 
                      PARTIC_CLIENTE, CL_SORTEO
FROM         CF_DISA_HIST.dbo.TCF16FI_H
WHERE     (T_OPERACION = 'C') AND (LEFT(CL_TARJETA, 6) = '700428')
GO

USE [CF_DISA]
GO
/****** Object:  View [dbo].[TodosCanjesTCD]    Script Date: 27/04/2017 12:40:00 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[TodosCanjesTCD]
AS
SELECT     CL_EMPRESA, C_VENTA, P_VENTA, N_VENTA, CL_OPERADOR, T_OPERACION, T_AUTORIZACION, E_OPERACION, FECHA, HORA, T_SOPORTE, 
                      F_CAPTURA, ID_CUENTA, CL_CLIENTE, CL_TARJETA, MEDIO_PAGO, IMPORTE, MONEDA, CL_EMPRESA_DOC, CL_DOCUMENTO, C_RESULTADO, 
                      NUM_AUT, N_REFERENCIA, FECH_CAD, CL_CA, TIEMPO_RESPUESTA, COD_RES_CA, C_VENTA_ORI, P_VENTA_ORI, N_VENTA_ORI, FECHA_ORI, 
                      N_REF_CLI, SALDO_PREV, SALDO_POST, CL_CAMPA, CL_CAMPA_EXT, ACTIV_TARJETA, CUMPLE_CLIENTE, MOTIVO_ANUL, BVENIDA_CLIENTE, 
                      PARTIC_CLIENTE, CL_SORTEO
FROM         dbo.TCF14FI
WHERE     (T_OPERACION = 'C') AND (LEFT(CL_TARJETA, 9) = '972400077')
UNION
SELECT     CL_EMPRESA, C_VENTA, P_VENTA, N_VENTA, CL_OPERADOR, T_OPERACION, T_AUTORIZACION, E_OPERACION, FECHA, HORA, T_SOPORTE, 
                      F_CAPTURA, ID_CUENTA, CL_CLIENTE, CL_TARJETA, MEDIO_PAGO, IMPORTE, MONEDA, CL_EMPRESA_DOC, CL_DOCUMENTO, C_RESULTADO, 
                      NUM_AUT, N_REFERENCIA, FECH_CAD, CL_CA, TIEMPO_RESPUESTA, COD_RES_CA, C_VENTA_ORI, P_VENTA_ORI, N_VENTA_ORI, FECHA_ORI, 
                      N_REF_CLI, SALDO_PREV, SALDO_POST, CL_CAMPA, CL_CAMPA_EXT, ACTIV_TARJETA, CUMPLE_CLIENTE, MOTIVO_ANUL, BVENIDA_CLIENTE, 
                      PARTIC_CLIENTE, CL_SORTEO
FROM         CF_DISA_HIST.dbo.TCF16FI_H
WHERE     (T_OPERACION = 'C') AND (LEFT(CL_TARJETA, 9) = '972400077')
GO

USE [CF_DISA]
GO
/****** Object:  View [dbo].[TodosCanjesTCD_SIMPLE]    Script Date: 27/04/2017 12:40:10 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[TodosCanjesTCD_SIMPLE]
AS
SELECT     ID_CUENTA
FROM         dbo.TCF14FI
WHERE     (T_OPERACION = 'C') AND (LEFT(CL_TARJETA, 9) = '972400077')
UNION
SELECT    ID_CUENTA
FROM         CF_DISA_HIST.dbo.TCF16FI_H
WHERE     (T_OPERACION = 'C') AND (LEFT(CL_TARJETA, 9) = '972400077')

GO

USE [CF_DISA]
GO
/****** Object:  View [dbo].[VW_AFR_5_CF]    Script Date: 27/04/2017 12:40:21 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[VW_AFR_5_CF]
AS
SELECT        TOP (100) PERCENT dbo.TCF14CI.C_VENTA AS [EESS CF], dbo.TCF14CI.CL_EMPRESA AS [EMP CF], dbo.TCF14CI.P_VENTA AS TERMINAL, LEFT(dbo.TCF11.COD_ESTABL, 4) AS ERS, RIGHT(dbo.TCF14CI.FECHA, 
                         2) + '/' + SUBSTRING(dbo.TCF14CI.FECHA, 5, 2) + '/' + LEFT(dbo.TCF14CI.FECHA, 4) AS FECHA, LEFT(dbo.TCF14CI.HORA, 2) + ':' + SUBSTRING(dbo.TCF14CI.HORA, 3, 2) + ':' + RIGHT(dbo.TCF14CI.HORA, 2) 
                         AS HORA, dbo.TCF65.ID_MOV AS [ID MOV], dbo.TCF14CI.N_VENTA AS [NRO TRX], LEFT(dbo.TCF14CI.NUM_AUT, 6) AS [COD AUT], dbo.TCF14CI.N_REFERENCIA AS [NRO OP SERVIDOR], 
                         dbo.TCF14CI.F_CAPTURA AS [TIPO CAPTURA], LEFT(dbo.TCF14CI.CL_TARJETA, 19) AS TARJETA, CASE WHEN SUBSTRING(dbo.TCF14CI.CL_TARJETA, 5, 2) = '21' THEN SUBSTRING(dbo.TCF14CI.CL_TARJETA, 10, 
                         6) ELSE '' END AS 'CLIENTE', SUBSTRING(dbo.TCF14CI.CL_TARJETA, 5, 2) AS PAIS, dbo.TCF14CI.CL_DOCUMENTO AS [TIPO TARJ], CONVERT(MONEY, dbo.TCF14CI.IMPORTE / 100, 1) AS [IMP TOTAL ART], 
                         LEFT(dbo.TCF66.CL_ARTI, 3) AS ARTICULO, CASE WHEN (dbo.TCF66.CL_ARTI BETWEEN '121' AND '133') THEN '1OIL' ELSE '2NOI' END AS TIPO, CONVERT(MONEY, dbo.TCF66.UNIDADES, 1) AS UNIDADES, 
                         CONVERT(MONEY, dbo.TCF66.PRECIO_UNIDAD / 10000, 2) AS [PVP UNITARIO], CONVERT(MONEY, dbo.TCF66.IMPORTE / 100, 1) AS [IMP PARCIAL ART], CASE WHEN SUBSTRING(dbo.TCF14CI.CL_TARJETA, 5, 2) 
                         <> '21' THEN '1I' WHEN FK_Codigo_SalesRep BETWEEN 'S11' AND 'S15' THEN '3F' WHEN FK_Codigo_SalesRep NOT BETWEEN 'S11' AND 
                         'S15' THEN '2C' WHEN dbo.TCF14CI.CL_DOCUMENTO = 'ESNL02' THEN '3F' ELSE '2C' END AS NEG
FROM            dbo.TCF14CI INNER JOIN
                         dbo.TCF65 ON dbo.TCF14CI.FECHA = dbo.TCF65.FECHA_MOV AND dbo.TCF14CI.HORA = dbo.TCF65.HORA_MOV AND dbo.TCF14CI.N_VENTA = dbo.TCF65.N_VENTA AND 
                         dbo.TCF14CI.CL_EMPRESA = dbo.TCF65.CL_EMPRESA AND dbo.TCF14CI.C_VENTA = dbo.TCF65.CL_CENTRO INNER JOIN
                         dbo.TCF66 ON dbo.TCF65.ID_MOV = dbo.TCF66.ID_MOV INNER JOIN
                         dbo.TCF11 ON dbo.TCF14CI.C_VENTA = dbo.TCF11.CL_CENTRO AND dbo.TCF14CI.CL_EMPRESA = dbo.TCF11.CL_EMPRESA AND dbo.TCF14CI.CL_CA = dbo.TCF11.CL_CA FULL OUTER JOIN
                         Euroshell.dbo.Clientes ON CONVERT(INTEGER, SUBSTRING(dbo.TCF14CI.CL_TARJETA, 10, 6)) = CONVERT(INTEGER, Euroshell.dbo.Clientes.EuroshellAccount)
WHERE        (dbo.TCF14CI.FECHA BETWEEN '20160500' AND '20160599') AND (LEFT(dbo.TCF14CI.CL_DOCUMENTO, 2) = 'ES') AND (dbo.TCF14CI.T_OPERACION = 'C') AND (dbo.TCF14CI.E_OPERACION = 'R') AND 
                         (dbo.TCF14CI.C_RESULTADO = '000')
GO

USE [CF_DISA]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[VW_DQ_Clientes]
AS
SELECT        
CL_CLIENTE,
RAZON_SOCIAL,
NOMBRE,
APELLIDO1,
APELLIDO2,
FECH_NAC,
DOCID,
TEL_FIJO,
TEL_MOVIL,
CP,
LOCALIDAD,
PROVINCIA,
SEXO,
ESTADO_CIVIL,
NUM_HIJOS,
TIPO_VEHICULO,
TIPO_COMBUS,
KILOMETROS,
CANAL_CAPTACION,
CODIGO_CAPTADOR,
CL_COLECTIVO,
FECH_ALTA,
CL_EMPRESA_HAB,
CL_CENTRO_HAB,
DATOS_COMPLETOS,
BIENVENIDA,
EMAIL,
REPOSTAJE_HAB,
PAIS,
ENVIO_PUBLICIDAD,
CL_REGLA_COD
FROM            dbo.TCF40
WHERE        (CL_CLIENTE IN
                             (SELECT DISTINCT CL_CLIENTE
                               FROM            dbo.TCF41
                               WHERE        (LEFT(CL_TARJETA, 9) = '972400077')))
GO

USE [CF_DISA]
GO
/****** Object:  View [dbo].[VW_DQ_EmpresasCentros]    Script Date: 27/04/2017 12:40:43 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[VW_DQ_EmpresasCentros]
AS
SELECT        CL_EMPRESA, CL_CENTRO, DESCRIPCION, DIRECCION, CP, LOCALIDAD, PROVINCIA, TEL_FIJO, TEL_MOVIL, FAX, EMAIL, CATALOGO_PROPIO, CL_AGRUPACION, COMPROBAR_OPERADOR, DATO_ADICIONAL1, 
                         DATO_ADICIONAL2, PERS_CONTACTO, ESTADO, MODO_FACTURA, SOLICITAR_CVV, DESFASE_HORA_SRV, CL_CIFRADO_MAC
FROM            dbo.TCF04
GO

USE [CF_DISA]
GO
/****** Object:  View [dbo].[VW_DQ_Transacciones_Desglose]    Script Date: 27/04/2017 12:40:51 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[VW_DQ_Transacciones_Desglose]
AS
select * from tcf67 
where tcf67.fecha >= '20141001' and tcf67.fecha <= '20161031'
union
select * from cf_disa_hist.dbo.tcf67_h
where cf_disa_hist.dbo.tcf67_h.fecha >= '20141001' and cf_disa_hist.dbo.tcf67_h.fecha <= '20161031'
GO


USE [CF_DISA]
GO
/****** Object:  View [dbo].[VW_DQ_Transacciones_Desglose2]    Script Date: 27/04/2017 12:40:59 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[VW_DQ_Transacciones_Desglose2]
AS
select * from tcf67 
where tcf67.fecha >= '20161101' and tcf67.fecha <= '20161231'
union
select * from cf_disa_hist.dbo.tcf67_h
where cf_disa_hist.dbo.tcf67_h.fecha >= '20161101' and cf_disa_hist.dbo.tcf67_h.fecha <= '20161231'
GO

USE [CF_DISA]
GO
/****** Object:  View [dbo].[VW_DQ_TransaccionesFI]    Script Date: 27/04/2017 12:41:07 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[VW_DQ_TransaccionesFI]
AS
select * from tcf14fi 
where left(cl_tarjeta,9) = '972400077'
and tcf14fi.fecha >= '20141001' and tcf14fi.fecha <= '20161031'  and E_OPERACION = 'R'
union
select 
[CL_EMPRESA]      ,[C_VENTA]      ,[P_VENTA]      ,[N_VENTA]      ,[CL_OPERADOR]      ,[T_OPERACION]
      ,[T_AUTORIZACION]      ,[E_OPERACION]      ,[FECHA]      ,[HORA]      ,[T_SOPORTE]      ,[F_CAPTURA]
      ,[ID_CUENTA]      ,[CL_CLIENTE]      ,[CL_TARJETA]      ,[MEDIO_PAGO]      ,[IMPORTE]
      ,[MONEDA]      ,[CL_EMPRESA_DOC]      ,[CL_DOCUMENTO]      ,[C_RESULTADO]      ,[NUM_AUT]
      ,[N_REFERENCIA]      ,[FECH_CAD]      ,[CL_CA]      ,[TIEMPO_RESPUESTA]      ,[COD_RES_CA]      ,[C_VENTA_ORI]
      ,[P_VENTA_ORI]      ,[N_VENTA_ORI]      ,[FECHA_ORI]      ,[N_REF_CLI]      ,[SALDO_PREV]      ,[SALDO_POST]
      ,[CL_CAMPA]      ,[CL_CAMPA_EXT]      ,[ACTIV_TARJETA]      ,[CUMPLE_CLIENTE]      ,[MOTIVO_ANUL]
      ,[BVENIDA_CLIENTE]      ,[PARTIC_CLIENTE]      ,[CL_SORTEO]      ,[IMPORTE_FIDEL]      ,[DESCUENTO]
      ,[NUM_PART_SORTEO]      ,[FECHA_PROCESO]      ,[HORA_PROCESO]      ,[TIPO_ACUM]      ,[SALDO_POST_DTO]
      ,[VALE_DESCUENTO]      ,[PROMOCION]      ,[PUNTOS_PROMO]      ,[ID_CUENTA_RECEP]
from cf_disa_hist.dbo.tcf16fi_h
where left(cl_tarjeta,9) = '972400077'
and cf_disa_hist.dbo.tcf16fi_h.fecha >= '20141001' and cf_disa_hist.dbo.tcf16fi_h.fecha <= '20161031' and E_OPERACION = 'R'
GO

USE [CF_DISA]
GO
/****** Object:  View [dbo].[VW_DQ_TransaccionesFI2]    Script Date: 27/04/2017 12:41:16 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE VIEW [dbo].[VW_DQ_TransaccionesFI2]
AS
select * from tcf14fi 
where left(cl_tarjeta,9) = '972400077'
and tcf14fi.fecha >= '20161101' and tcf14fi.fecha <= '20161231'  and E_OPERACION = 'R'
union
select 
[CL_EMPRESA]      ,[C_VENTA]      ,[P_VENTA]      ,[N_VENTA]      ,[CL_OPERADOR]      ,[T_OPERACION]
      ,[T_AUTORIZACION]      ,[E_OPERACION]      ,[FECHA]      ,[HORA]      ,[T_SOPORTE]      ,[F_CAPTURA]
      ,[ID_CUENTA]      ,[CL_CLIENTE]      ,[CL_TARJETA]      ,[MEDIO_PAGO]      ,[IMPORTE]
      ,[MONEDA]      ,[CL_EMPRESA_DOC]      ,[CL_DOCUMENTO]      ,[C_RESULTADO]      ,[NUM_AUT]
      ,[N_REFERENCIA]      ,[FECH_CAD]      ,[CL_CA]      ,[TIEMPO_RESPUESTA]      ,[COD_RES_CA]      ,[C_VENTA_ORI]
      ,[P_VENTA_ORI]      ,[N_VENTA_ORI]      ,[FECHA_ORI]      ,[N_REF_CLI]      ,[SALDO_PREV]      ,[SALDO_POST]
      ,[CL_CAMPA]      ,[CL_CAMPA_EXT]      ,[ACTIV_TARJETA]      ,[CUMPLE_CLIENTE]      ,[MOTIVO_ANUL]
      ,[BVENIDA_CLIENTE]      ,[PARTIC_CLIENTE]      ,[CL_SORTEO]      ,[IMPORTE_FIDEL]      ,[DESCUENTO]
      ,[NUM_PART_SORTEO]      ,[FECHA_PROCESO]      ,[HORA_PROCESO]      ,[TIPO_ACUM]      ,[SALDO_POST_DTO]
      ,[VALE_DESCUENTO]      ,[PROMOCION]      ,[PUNTOS_PROMO]      ,[ID_CUENTA_RECEP]
from cf_disa_hist.dbo.tcf16fi_h
where left(cl_tarjeta,9) = '972400077'
and cf_disa_hist.dbo.tcf16fi_h.fecha >= '20161101' and cf_disa_hist.dbo.tcf16fi_h.fecha <= '20161231' and E_OPERACION = 'R'
GO

USE [CF_DISA]
GO
/****** Object:  View [dbo].[VW_GYT_ARTI]    Script Date: 27/04/2017 12:41:24 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
create VIEW [dbo].[VW_GYT_ARTI]
WITH SCHEMABINDING
AS
SELECT     RTRIM(LTRIM(CL_ARTI)) AS CL_ARTI, DARTI
FROM         dbo.TCF48
GO

USE [CF_DISA]
GO
/****** Object:  View [dbo].[VW_GYT_CLI4DOC]    Script Date: 27/04/2017 12:41:33 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE VIEW [dbo].[VW_GYT_CLI4DOC]
WITH SCHEMABINDING
AS
SELECT     DOCID, TIPO_DOCID, NOMBRE, APELLIDO1, APELLIDO2, CL_CENTRO_HAB, CL_EMPRESA_HAB, COUNT_BIG(*) AS COUNT
FROM         dbo.TCF40
inner join dbo.tcf42 on tcf42.CL_CLIENTE = tcf40.CL_CLIENTE
WHERE     (DOCID IS NOT NULL) AND (LEN(RTRIM(LTRIM(DOCID))) > 1) AND (NOMBRE IS NOT NULL) AND (APELLIDO1 IS NOT NULL) AND 
                      (APELLIDO2 IS NOT NULL) AND (LEN(RTRIM(LTRIM(NOMBRE))) > 0) AND (LEN(RTRIM(LTRIM(APELLIDO1))) > 0) AND (LEN(RTRIM(LTRIM(APELLIDO2))) 
                      > 0) and tcf42.TIPO_CUENTA='FI'
GROUP BY DOCID, TIPO_DOCID, NOMBRE, APELLIDO1, APELLIDO2, CL_CENTRO_HAB, CL_EMPRESA_HAB
GO

USE [CF_DISA]
GO
/****** Object:  View [dbo].[VW_GYT_FI_DATA]    Script Date: 27/04/2017 12:41:41 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[VW_GYT_FI_DATA]
WITH SCHEMABINDING 
AS
SELECT     dbo.TCF40.CL_CLIENTE, dbo.TCF41.ID_CUENTA, dbo.TCF41.CL_TARJETA, dbo.TCF40.NOMBRE, dbo.TCF40.APELLIDO1, dbo.TCF40.APELLIDO2, 
                      dbo.TCF40.TIPO_DOCID, dbo.TCF40.DOCID, dbo.TCF40.EMAIL, dbo.TCF40.TEL_FIJO, dbo.TCF40.TEL_MOVIL, COUNT_BIG(*) AS COUNT, 
                      dbo.TCF40.FAX, dbo.TCF40.CP, dbo.TCF40.LOCALIDAD, dbo.TCF40.PROVINCIA, dbo.TCF40.DIRECCION, dbo.TCF40.FECH_NAC, 
                      dbo.TCF42.ESTADO AS CUENTA_ESTADO, dbo.TCF41.ESTADO AS TARJETA_ESTADO, dbo.TCF40.FECH_ALTA, CL_CENTRO_HAB, CL_EMPRESA_HAB, dbo.TCF42.SALDO_PUNTOS as PUNTOS_CUENTA

FROM         dbo.TCF40 INNER JOIN
                      dbo.TCF41 ON dbo.TCF40.CL_CLIENTE = dbo.TCF41.CL_CLIENTE INNER JOIN
                      dbo.TCF42 ON dbo.TCF41.ID_CUENTA = dbo.TCF42.ID_CUENTA
WHERE     (LEFT(dbo.TCF41.CL_TARJETA, 6) = '700421') OR
                      (LEFT(dbo.TCF41.CL_TARJETA, 9) = '972400077')
					  OR
                      (LEFT(dbo.TCF41.CL_TARJETA, 6) = '700428')
GROUP BY dbo.TCF40.CL_CLIENTE, dbo.TCF41.ID_CUENTA, dbo.TCF41.CL_TARJETA, dbo.TCF40.NOMBRE, dbo.TCF40.APELLIDO1, dbo.TCF40.APELLIDO2, 
                      dbo.TCF40.TIPO_DOCID, dbo.TCF40.DOCID, dbo.TCF40.EMAIL, dbo.TCF40.TEL_FIJO, dbo.TCF40.TEL_MOVIL, dbo.TCF40.FAX, dbo.TCF40.CP, 
                      dbo.TCF40.LOCALIDAD, dbo.TCF40.PROVINCIA, dbo.TCF40.DIRECCION, dbo.TCF40.FECH_NAC, dbo.TCF42.ESTADO, dbo.TCF41.ESTADO, 
                      dbo.TCF40.FECH_ALTA, CL_CENTRO_HAB, CL_EMPRESA_HAB,dbo.TCF42.SALDO_PUNTOS
GO

USE [CF_DISA]
GO
/****** Object:  View [dbo].[VW_GYT_FI_TAR4NUM]    Script Date: 27/04/2017 12:41:48 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[VW_GYT_FI_TAR4NUM]
WITH SCHEMABINDING
AS
SELECT     CL_TARJETA
FROM         dbo.TCF41
WHERE     (LEFT(CL_TARJETA, 6) = '700421') OR
                      (LEFT(CL_TARJETA, 9) = '972400077') OR
                      (LEFT(CL_TARJETA, 6) = '700428')

GO

USE [CF_DISA]
GO
/****** Object:  View [dbo].[VW_GYT_FI_TRAN]    Script Date: 27/04/2017 12:41:56 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[VW_GYT_FI_TRAN]
WITH SCHEMABINDING 
AS
SELECT DISTINCT 
                      'NO_HIST' AS HIST, RTRIM(dbo.TCF14FI.CL_EMPRESA) + '_' + RTRIM(dbo.TCF14FI.CL_CLIENTE) + '_' + RTRIM(dbo.TCF14FI.ID_CUENTA) 
                      + '_' + RTRIM(dbo.TCF14FI.CL_TARJETA) + '_' + RTRIM(dbo.TCF14FI.C_VENTA) + '_' + RTRIM(dbo.TCF14FI.P_VENTA) 
                      + '_' + RTRIM(dbo.TCF14FI.N_VENTA) + '_' + RTRIM(dbo.TCF14FI.T_OPERACION) + '_' + RTRIM(dbo.TCF14FI.E_OPERACION) 
                      + '_' + RTRIM(dbo.TCF14FI.FECHA) + '_' + RTRIM(dbo.TCF14FI.HORA) AS PK_CODIGO, dbo.TCF14FI.CL_EMPRESA, dbo.TCF14FI.CL_CLIENTE, 
                      dbo.TCF14FI.ID_CUENTA, dbo.TCF14FI.C_VENTA, dbo.TCF14FI.P_VENTA, dbo.TCF14FI.N_VENTA, dbo.TCF14FI.T_OPERACION, 
                      dbo.TCF14FI.E_OPERACION, dbo.TCF14FI.FECHA, dbo.TCF14FI.HORA, dbo.TCF14FI.CL_TARJETA, dbo.TCF14FI.SALDO_PREV, 
                      dbo.TCF14FI.SALDO_POST, dbo.TCF14FI.SALDO_POST - dbo.TCF14FI.SALDO_PREV AS PUNTOS, dbo.TCF14FI.MOTIVO_ANUL, dbo.TCF40.DOCID, 
                      dbo.TCF40.TIPO_DOCID, dbo.TCF40.NOMBRE, dbo.TCF40.APELLIDO1, dbo.TCF40.APELLIDO2, dbo.TCF04.DESCRIPCION AS ESTACION, 
                      dbo.TCF67.UNIDADES, dbo.TCF40.FAX, dbo.TCF40.DIRECCION, dbo.TCF40.CP, dbo.TCF40.LOCALIDAD, dbo.TCF40.PROVINCIA, dbo.TCF40.FECH_ALTA, 
                      dbo.TCF40.FECH_NAC, dbo.TCF42.ESTADO AS CUENTA_ESTADO, dbo.TCF41.ESTADO AS TARJETA_ESTADO, dbo.TCF40.EMAIL, dbo.TCF40.TEL_FIJO, 
                      dbo.TCF40.TEL_MOVIL, dbo.TCF42.SALDO_PUNTOS as PUNTOS_CUENTA
FROM         dbo.TCF14FI INNER JOIN
                     
                      dbo.TCF04 ON dbo.TCF14FI.CL_EMPRESA = dbo.TCF04.CL_EMPRESA AND dbo.TCF14FI.C_VENTA = dbo.TCF04.CL_CENTRO INNER JOIN
                      dbo.TCF11 ON dbo.TCF04.CL_EMPRESA = dbo.TCF11.CL_EMPRESA AND dbo.TCF04.CL_CENTRO = dbo.TCF11.CL_CENTRO AND 
                      dbo.TCF14FI.CL_CA = dbo.TCF11.CL_CA AND dbo.TCF11.CL_CA = '000001' INNER JOIN
                      dbo.TCF67 ON dbo.TCF14FI.CL_EMPRESA = dbo.TCF67.CL_EMPRESA AND dbo.TCF14FI.C_VENTA = dbo.TCF67.CL_CENTRO AND 
                      dbo.TCF14FI.P_VENTA = dbo.TCF67.CL_TPV AND dbo.TCF14FI.N_VENTA = dbo.TCF67.N_VENTA AND 
                      dbo.TCF14FI.FECHA = dbo.TCF67.FECHA INNER JOIN
                      
                      dbo.TCF41 ON dbo.TCF14FI.CL_TARJETA = dbo.TCF41.CL_TARJETA
					  inner join  dbo.TCF40 ON dbo.TCF41.CL_CLIENTE = dbo.TCF40.CL_CLIENTE 
					  inner join dbo.TCF42 ON dbo.TCF41.ID_CUENTA = dbo.TCF42.ID_CUENTA 
WHERE     (dbo.TCF14FI.C_RESULTADO = '000') AND (LEFT(dbo.TCF14FI.CL_TARJETA, 6) = '700421' OR
                      LEFT(dbo.TCF14FI.CL_TARJETA, 9) = '972400077' OR
                      LEFT(dbo.TCF14FI.CL_TARJETA, 6) = '700428') AND (dbo.TCF14FI.E_OPERACION = 'R') AND (dbo.TCF14FI.CL_EMPRESA IS NOT NULL) AND 
                      (dbo.TCF14FI.CL_CLIENTE IS NOT NULL) AND (dbo.TCF14FI.ID_CUENTA IS NOT NULL) AND (dbo.TCF14FI.C_VENTA IS NOT NULL) AND 
                      (dbo.TCF14FI.P_VENTA IS NOT NULL) AND (dbo.TCF14FI.N_VENTA IS NOT NULL) AND (dbo.TCF14FI.T_OPERACION IS NOT NULL) AND 
                      (dbo.TCF14FI.E_OPERACION IS NOT NULL) AND (dbo.TCF14FI.FECHA IS NOT NULL) AND (dbo.TCF14FI.HORA IS NOT NULL) AND 
                      (dbo.TCF14FI.CL_TARJETA IS NOT NULL) AND (dbo.TCF40.TIPO_DOCID IS NOT NULL)
GO

USE [CF_DISA]
GO

/****** Object:  View [dbo].[VW_GYT_FI_TRAN_20160217]    Script Date: 27/04/2017 12:42:05 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[VW_GYT_FI_TRAN_20160217]
WITH SCHEMABINDING 
AS
SELECT DISTINCT 
                      'NO_HIST' AS HIST, RTRIM(dbo.TCF14FI.CL_EMPRESA) + '_' + RTRIM(dbo.TCF14FI.CL_CLIENTE) + '_' + RTRIM(dbo.TCF14FI.ID_CUENTA) 
                      + '_' + RTRIM(dbo.TCF14FI.CL_TARJETA) + '_' + RTRIM(dbo.TCF14FI.C_VENTA) + '_' + RTRIM(dbo.TCF14FI.P_VENTA) 
                      + '_' + RTRIM(dbo.TCF14FI.N_VENTA) + '_' + RTRIM(dbo.TCF14FI.T_OPERACION) + '_' + RTRIM(dbo.TCF14FI.E_OPERACION) 
                      + '_' + RTRIM(dbo.TCF14FI.FECHA) + '_' + RTRIM(dbo.TCF14FI.HORA) AS PK_CODIGO, dbo.TCF14FI.CL_EMPRESA, dbo.TCF14FI.CL_CLIENTE, 
                      dbo.TCF14FI.ID_CUENTA, dbo.TCF14FI.C_VENTA, dbo.TCF14FI.P_VENTA, dbo.TCF14FI.N_VENTA, dbo.TCF14FI.T_OPERACION, 
                      dbo.TCF14FI.E_OPERACION, dbo.TCF14FI.FECHA, dbo.TCF14FI.HORA, dbo.TCF14FI.CL_TARJETA, dbo.TCF14FI.SALDO_PREV, 
                      dbo.TCF14FI.SALDO_POST, dbo.TCF14FI.SALDO_POST - dbo.TCF14FI.SALDO_PREV AS PUNTOS, dbo.TCF14FI.MOTIVO_ANUL, dbo.TCF40.DOCID, 
                      dbo.TCF40.TIPO_DOCID, dbo.TCF40.NOMBRE, dbo.TCF40.APELLIDO1, dbo.TCF40.APELLIDO2, dbo.TCF04.DESCRIPCION AS ESTACION, 
                      dbo.TCF67.UNIDADES, dbo.TCF40.FAX, dbo.TCF40.DIRECCION, dbo.TCF40.CP, dbo.TCF40.LOCALIDAD, dbo.TCF40.PROVINCIA, dbo.TCF40.FECH_ALTA, 
                      dbo.TCF40.FECH_NAC, dbo.TCF42.ESTADO AS CUENTA_ESTADO, dbo.TCF41.ESTADO AS TARJETA_ESTADO, dbo.TCF40.EMAIL, dbo.TCF40.TEL_FIJO, 
                      dbo.TCF40.TEL_MOVIL, dbo.TCF42.SALDO_PUNTOS as PUNTOS_CUENTA
FROM         dbo.TCF14FI INNER JOIN
                      dbo.TCF40 ON dbo.TCF14FI.CL_CLIENTE = dbo.TCF40.CL_CLIENTE INNER JOIN
                      dbo.TCF04 ON dbo.TCF14FI.CL_EMPRESA = dbo.TCF04.CL_EMPRESA AND dbo.TCF14FI.C_VENTA = dbo.TCF04.CL_CENTRO INNER JOIN
                      dbo.TCF11 ON dbo.TCF04.CL_EMPRESA = dbo.TCF11.CL_EMPRESA AND dbo.TCF04.CL_CENTRO = dbo.TCF11.CL_CENTRO AND 
                      dbo.TCF14FI.CL_CA = dbo.TCF11.CL_CA AND dbo.TCF11.CL_CA = '000001' INNER JOIN
                      dbo.TCF67 ON dbo.TCF14FI.CL_EMPRESA = dbo.TCF67.CL_EMPRESA AND dbo.TCF14FI.C_VENTA = dbo.TCF67.CL_CENTRO AND 
                      dbo.TCF14FI.P_VENTA = dbo.TCF67.CL_TPV AND dbo.TCF14FI.N_VENTA = dbo.TCF67.N_VENTA AND 
                      dbo.TCF14FI.FECHA = dbo.TCF67.FECHA INNER JOIN
                      dbo.TCF42 ON dbo.TCF14FI.ID_CUENTA = dbo.TCF42.ID_CUENTA INNER JOIN
                      dbo.TCF41 ON dbo.TCF14FI.CL_TARJETA = dbo.TCF41.CL_TARJETA




WHERE     (dbo.TCF14FI.C_RESULTADO = '000') AND (LEFT(dbo.TCF14FI.CL_TARJETA, 6) = '700421' OR
                      LEFT(dbo.TCF14FI.CL_TARJETA, 9) = '972400077' OR
                      LEFT(dbo.TCF14FI.CL_TARJETA, 6) = '700428') AND (dbo.TCF14FI.E_OPERACION = 'R') AND (dbo.TCF14FI.CL_EMPRESA IS NOT NULL) AND 
                      (dbo.TCF14FI.CL_CLIENTE IS NOT NULL) AND (dbo.TCF14FI.ID_CUENTA IS NOT NULL) AND (dbo.TCF14FI.C_VENTA IS NOT NULL) AND 
                      (dbo.TCF14FI.P_VENTA IS NOT NULL) AND (dbo.TCF14FI.N_VENTA IS NOT NULL) AND (dbo.TCF14FI.T_OPERACION IS NOT NULL) AND 
                      (dbo.TCF14FI.E_OPERACION IS NOT NULL) AND (dbo.TCF14FI.FECHA IS NOT NULL) AND (dbo.TCF14FI.HORA IS NOT NULL) AND 
                      (dbo.TCF14FI.CL_TARJETA IS NOT NULL) AND (dbo.TCF40.TIPO_DOCID IS NOT NULL)
GO

USE [CF_DISA]
GO
/****** Object:  View [dbo].[VW_GYT_FI_TRAN_ADESIS]    Script Date: 27/04/2017 12:42:20 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE view [dbo].[VW_GYT_FI_TRAN_ADESIS] 
WITH SCHEMABINDING 
AS
SELECT dbo.TCF11.CL_CA AS CL_CA,       
		       dbo.TCF14FI.CL_CLIENTE AS CL_CLIENTE,   
		       dbo.TCF14FI.ID_CUENTA AS ID_CUENTA,    
		       dbo.TCF14FI.N_VENTA AS N_VENTA,   
		       dbo.TCF14FI.FECHA AS FECHA,   
		       dbo.TCF14FI.HORA AS HORA,   
		       dbo.TCF14FI.CL_TARJETA AS CL_TARJETA,   
		       dbo.TCF11.COD_ESTABL AS COD_ESTABL,   
		       dbo.TCF04.DESCRIPCION AS ESTACION,    
		       dbo.TCF42.SALDO_PUNTOS AS SALDO_PUNTOS,   
		       dbo.TCF14FI.CL_CAMPA AS CL_CAMPA,   
		       dbo.TCF14FI.P_VENTA AS P_VENTA,    
		       dbo.TCF14FI.C_VENTA AS C_VENTA,   
		       dbo.TCF14FI.CL_EMPRESA AS CL_EMPRESA,   
		       CAST(dbo.TCF67.UNIDADES AS MONEY) AS UNIDADES,   
		       dbo.TCF48.DARTI AS ArticuloM,   
		       TCF48_1.DARTI AS ArticuloC,   
		       dbo.TCF14FI.T_OPERACION AS T_OPERACION,   
		       dbo.TCF67.IMPORTE AS IMPORTE,   
		       sum(dbo.TCF67.PUNTOS) AS PUNTOSM,   
		       dbo.TCF14FI.SALDO_PREV AS SALDO_PREV,   
		       dbo.TCF14FI.SALDO_POST AS SALDO_POST,   
		       dbo.TCF49.PUNTOS AS PUNTOSC,   
		       CAST(ABS(dbo.TCF49.UNIDADES) AS MONEY) AS UNIDADESCANJE,   
		       dbo.TCF48.CL_ARTI AS CODPRODUCTO,   
		       TCF48_1.CL_ARTI AS CODREGALO    
		FROM dbo.TCF49 INNER JOIN   
		     dbo.TCF48 TCF48_1 ON dbo.TCF49.CL_REGALO = TCF48_1.CL_ARTI RIGHT OUTER JOIN   
		     dbo.TCF14FI INNER JOIN   
		     dbo.TCF11 ON dbo.TCF14FI.CL_EMPRESA = dbo.TCF11.CL_EMPRESA AND dbo.TCF14FI.C_VENTA = dbo.TCF11.CL_CENTRO INNER JOIN   
		     dbo.TCF42 ON dbo.TCF14FI.ID_CUENTA = dbo.TCF42.ID_CUENTA INNER JOIN   
		     dbo.TCF04 ON dbo.TCF14FI.CL_EMPRESA = dbo.TCF04.CL_EMPRESA AND dbo.TCF14FI.C_VENTA = dbo.TCF04.CL_CENTRO ON    
		     dbo.TCF49.FECHA_MOV = dbo.TCF14FI.FECHA AND dbo.TCF49.HORA_MOV = dbo.TCF14FI.HORA AND   
		     dbo.TCF49.CL_EMPRESA = dbo.TCF14FI.CL_EMPRESA AND dbo.TCF49.CL_CENTRO = dbo.TCF14FI.C_VENTA AND    
		     dbo.TCF49.N_VENTA = dbo.TCF14FI.N_VENTA AND dbo.TCF49.CL_TPV = dbo.TCF14FI.P_VENTA AND    
		     dbo.TCF49.CL_CAMPA = dbo.TCF14FI.CL_CAMPA LEFT OUTER JOIN   
		     dbo.TCF48 INNER JOIN   
		     dbo.TCF67 ON dbo.TCF48.CL_ARTI = dbo.TCF67.CL_ARTI ON dbo.TCF14FI.N_VENTA = dbo.TCF67.N_VENTA AND    
		     dbo.TCF14FI.CL_CAMPA = dbo.TCF67.CL_CAMPA AND dbo.TCF14FI.P_VENTA = dbo.TCF67.CL_TPV AND    
		     dbo.TCF14FI.C_VENTA = dbo.TCF67.CL_CENTRO AND dbo.TCF14FI.CL_EMPRESA = dbo.TCF67.CL_EMPRESA AND    
		     dbo.TCF14FI.FECHA = dbo.TCF67.FECHA   
		WHERE 
		      (dbo.TCF11.CL_CA = '000001')   
		      AND dbo.TCF14FI.C_RESULTADO = '000'   
		      AND (dbo.TCF14FI.T_OPERACION IN ('M','A'))  
			  group by dbo.TCF11.CL_CA, dbo.TCF14FI.CL_CLIENTE,dbo.TCF14FI.ID_CUENTA,dbo.TCF14FI.N_VENTA,
dbo.TCF14FI.FECHA, dbo.TCF14FI.HORA, dbo.TCF14FI.CL_TARJETA, dbo.TCF11.COD_ESTABL, dbo.TCF04.DESCRIPCION,
dbo.TCF42.SALDO_PUNTOS, dbo.TCF14FI.CL_CAMPA, dbo.TCF14FI.P_VENTA, dbo.TCF14FI.C_VENTA, dbo.TCF14FI.CL_EMPRESA, 
dbo.TCF67.UNIDADES, dbo.TCF48.DARTI, TCF48_1.DARTI, dbo.TCF14FI.T_OPERACION, dbo.TCF67.IMPORTE, 
dbo.TCF14FI.SALDO_PREV, dbo.TCF14FI.SALDO_POST, dbo.TCF49.PUNTOS,dbo.TCF49.UNIDADES,dbo.TCF48.CL_ARTI,TCF48_1.CL_ARTI
		UNION  ALL
		SELECT dbo.TCF11.CL_CA AS CL_CA,         
		       dbo.TCF14FI.CL_CLIENTE AS CL_CLIENTE,   
		       dbo.TCF14FI.ID_CUENTA AS ID_CUENTA,    
		       dbo.TCF14FI.N_VENTA AS N_VENTA,   
		       dbo.TCF14FI.FECHA AS FECHA,   
		       dbo.TCF14FI.HORA AS HORA,   
		       dbo.TCF14FI.CL_TARJETA AS CL_TARJETA,   
		       dbo.TCF11.COD_ESTABL AS COD_ESTABL,   
		       dbo.TCF04.DESCRIPCION AS ESTACION,    
		       dbo.TCF42.SALDO_PUNTOS AS SALDO_PUNTOS,   
		       dbo.TCF14FI.CL_CAMPA AS CL_CAMPA,   
		       dbo.TCF14FI.P_VENTA AS P_VENTA,    
		       dbo.TCF14FI.C_VENTA AS C_VENTA,   
		       dbo.TCF14FI.CL_EMPRESA AS CL_EMPRESA,   
		       CAST(dbo.TCF49.UNIDADES AS MONEY) AS UNIDADES,   
		       '' AS ArticuloM,   
		       dbo.TCF48.DARTI AS ArticuloC,   
		       dbo.TCF14FI.T_OPERACION AS T_OPERACION,   
		       0 AS IMPORTE,   
		       0 AS PUNTOSM,   
		       dbo.TCF14FI.SALDO_PREV AS SALDO_PREV,   
		       dbo.TCF14FI.SALDO_POST AS SALDO_POST,   
		       dbo.TCF49.PUNTOS AS PUNTOSC,   
		       CAST(ABS(dbo.TCF49.UNIDADES) AS MONEY) AS UNIDADESCANJE,   
		       '' AS CODPRODUCTO,   
		       dbo.TCF49.CL_REGALO AS CODREGALO    
		FROM dbo.TCF14FI INNER JOIN  
		     dbo.TCF49 ON dbo.TCF49.FECHA_MOV = dbo.TCF14FI.FECHA AND dbo.TCF49.HORA_MOV = dbo.TCF14FI.HORA AND   
		     dbo.TCF49.CL_EMPRESA = dbo.TCF14FI.CL_EMPRESA AND dbo.TCF49.CL_CENTRO = dbo.TCF14FI.C_VENTA AND    
		     dbo.TCF49.N_VENTA = dbo.TCF14FI.N_VENTA AND dbo.TCF49.CL_TPV = dbo.TCF14FI.P_VENTA     
		     INNER JOIN dbo.TCF48 ON dbo.TCF49.CL_REGALO = dbo.TCF48.CL_ARTI  
		     INNER JOIN dbo.TCF11 ON dbo.TCF14FI.CL_EMPRESA = dbo.TCF11.CL_EMPRESA AND dbo.TCF14FI.C_VENTA = dbo.TCF11.CL_CENTRO   
		     INNER JOIN dbo.TCF42 ON dbo.TCF14FI.ID_CUENTA = dbo.TCF42.ID_CUENTA   
		     INNER JOIN dbo.TCF04 ON dbo.TCF14FI.CL_EMPRESA = dbo.TCF04.CL_EMPRESA AND dbo.TCF14FI.C_VENTA = dbo.TCF04.CL_CENTRO     
		WHERE 
		      (dbo.TCF11.CL_CA = '000001')   
		      AND dbo.TCF14FI.C_RESULTADO = '000'   
              
		      AND (dbo.TCF14FI.T_OPERACION IN ('C','X') )  
GO

USE [CF_DISA]
GO
/****** Object:  View [dbo].[VW_TUX_CHEQ_TOTAL]    Script Date: 27/04/2017 12:42:29 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[VW_TUX_CHEQ_TOTAL]
AS
SELECT [N_DOCUMENTO]
      ,[TITULAR]
      ,[IMPORTE]
      ,[ESTADO]
      ,[FECHA_ALTA]
      ,[FECHA_CAD]
      ,[FECHA_COBRO]
      ,[HORA_COBRO]
      ,[FECHA_PROCESO]
      ,[HORA_PROCESO]
      ,[CL_EMPRESA]
      ,[CL_CENTRO]
      ,[CL_TPV]
      ,[N_VENTA]
      ,[TIPO_COBRO]
      ,[CL_TR]
      ,[CL_REGLA_COD]
  FROM [CF_DISA].[dbo].[TUX_CHEQ]
  UNION
SELECT [N_DOCUMENTO]
      ,[TITULAR]
      ,[IMPORTE]
      ,[ESTADO]
      ,[FECHA_ALTA]
      ,[FECHA_CAD]
      ,[FECHA_COBRO]
      ,[HORA_COBRO]
      ,[FECHA_PROCESO]
      ,[HORA_PROCESO]
      ,[CL_EMPRESA]
      ,[CL_CENTRO]
      ,[CL_TPV]
      ,[N_VENTA]
      ,[TIPO_COBRO]
      ,[CL_TR]
      ,[CL_REGLA_COD]
  FROM [CF_DISA_HIST].[dbo].[TUX_CHEQ_H]
GO


