USE [CF_DISA]
GO

/****** Object:  View [dbo].[VW_GYT_FI_TRAN_ADESIS]    Script Date: 11/05/2016 11:12:29 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO



CREATE view [dbo].[VW_GYT_FI_TRAN_ADESIS] 
WITH SCHEMABINDING 
AS
SELECT dbo.TCF11.CL_CA AS CL_CA,       
		       dbo.TCF14FI.CL_CLIENTE AS CL_CLIENTE,   
		       dbo.TCF14FI.ID_CUENTA AS ID_CUENTA,    
		       dbo.TCF14FI.N_VENTA AS N_VENTA,   
		       dbo.TCF14FI.FECHA AS FECHA,   
		       dbo.TCF14FI.HORA AS HORA,   
		       dbo.TCF14FI.CL_TARJETA AS CL_TARJETA,   
		       dbo.TCF11.COD_ESTABL AS COD_ESTABL,   
		       dbo.TCF04.DESCRIPCION AS ESTACION,    
		       dbo.TCF42.SALDO_PUNTOS AS SALDO_PUNTOS,   
		       dbo.TCF14FI.CL_CAMPA AS CL_CAMPA,   
		       dbo.TCF14FI.P_VENTA AS P_VENTA,    
		       dbo.TCF14FI.C_VENTA AS C_VENTA,   
		       dbo.TCF14FI.CL_EMPRESA AS CL_EMPRESA,   
		       CAST(dbo.TCF67.UNIDADES AS MONEY) AS UNIDADES,   
		       dbo.TCF48.DARTI AS ArticuloM,   
		       TCF48_1.DARTI AS ArticuloC,   
		       dbo.TCF14FI.T_OPERACION AS T_OPERACION,   
		       dbo.TCF67.IMPORTE AS IMPORTE,   
		       sum(dbo.TCF67.PUNTOS) AS PUNTOSM,   
		       dbo.TCF14FI.SALDO_PREV AS SALDO_PREV,   
		       dbo.TCF14FI.SALDO_POST AS SALDO_POST,   
		       dbo.TCF49.PUNTOS AS PUNTOSC,   
		       CAST(ABS(dbo.TCF49.UNIDADES) AS MONEY) AS UNIDADESCANJE,   
		       dbo.TCF48.CL_ARTI AS CODPRODUCTO,   
		       TCF48_1.CL_ARTI AS CODREGALO    
		FROM dbo.TCF49 INNER JOIN   
		     dbo.TCF48 TCF48_1 ON dbo.TCF49.CL_REGALO = TCF48_1.CL_ARTI RIGHT OUTER JOIN   
		     dbo.TCF14FI INNER JOIN   
		     dbo.TCF11 ON dbo.TCF14FI.CL_EMPRESA = dbo.TCF11.CL_EMPRESA AND dbo.TCF14FI.C_VENTA = dbo.TCF11.CL_CENTRO INNER JOIN   
		     dbo.TCF42 ON dbo.TCF14FI.ID_CUENTA = dbo.TCF42.ID_CUENTA INNER JOIN   
		     dbo.TCF04 ON dbo.TCF14FI.CL_EMPRESA = dbo.TCF04.CL_EMPRESA AND dbo.TCF14FI.C_VENTA = dbo.TCF04.CL_CENTRO ON    
		     dbo.TCF49.FECHA_MOV = dbo.TCF14FI.FECHA AND dbo.TCF49.HORA_MOV = dbo.TCF14FI.HORA AND   
		     dbo.TCF49.CL_EMPRESA = dbo.TCF14FI.CL_EMPRESA AND dbo.TCF49.CL_CENTRO = dbo.TCF14FI.C_VENTA AND    
		     dbo.TCF49.N_VENTA = dbo.TCF14FI.N_VENTA AND dbo.TCF49.CL_TPV = dbo.TCF14FI.P_VENTA AND    
		     dbo.TCF49.CL_CAMPA = dbo.TCF14FI.CL_CAMPA LEFT OUTER JOIN   
		     dbo.TCF48 INNER JOIN   
		     dbo.TCF67 ON dbo.TCF48.CL_ARTI = dbo.TCF67.CL_ARTI ON dbo.TCF14FI.N_VENTA = dbo.TCF67.N_VENTA AND    
		     dbo.TCF14FI.CL_CAMPA = dbo.TCF67.CL_CAMPA AND dbo.TCF14FI.P_VENTA = dbo.TCF67.CL_TPV AND    
		     dbo.TCF14FI.C_VENTA = dbo.TCF67.CL_CENTRO AND dbo.TCF14FI.CL_EMPRESA = dbo.TCF67.CL_EMPRESA AND    
		     dbo.TCF14FI.FECHA = dbo.TCF67.FECHA   
		WHERE 
		      (dbo.TCF11.CL_CA = '000001')   
		      AND dbo.TCF14FI.C_RESULTADO = '000'   
    	     
		      AND (dbo.TCF14FI.T_OPERACION IN ('M','A'))  
			  group by dbo.TCF11.CL_CA, dbo.TCF14FI.CL_CLIENTE,dbo.TCF14FI.ID_CUENTA,dbo.TCF14FI.N_VENTA,
dbo.TCF14FI.FECHA, dbo.TCF14FI.HORA, dbo.TCF14FI.CL_TARJETA, dbo.TCF11.COD_ESTABL, dbo.TCF04.DESCRIPCION,
dbo.TCF42.SALDO_PUNTOS, dbo.TCF14FI.CL_CAMPA, dbo.TCF14FI.P_VENTA, dbo.TCF14FI.C_VENTA, dbo.TCF14FI.CL_EMPRESA, 
dbo.TCF67.UNIDADES, dbo.TCF48.DARTI, TCF48_1.DARTI, dbo.TCF14FI.T_OPERACION, dbo.TCF67.IMPORTE, 
dbo.TCF14FI.SALDO_PREV, dbo.TCF14FI.SALDO_POST, dbo.TCF49.PUNTOS,dbo.TCF49.UNIDADES,dbo.TCF48.CL_ARTI,TCF48_1.CL_ARTI
		UNION  ALL
		SELECT dbo.TCF11.CL_CA AS CL_CA,         
		       dbo.TCF14FI.CL_CLIENTE AS CL_CLIENTE,   
		       dbo.TCF14FI.ID_CUENTA AS ID_CUENTA,    
		       dbo.TCF14FI.N_VENTA AS N_VENTA,   
		       dbo.TCF14FI.FECHA AS FECHA,   
		       dbo.TCF14FI.HORA AS HORA,   
		       dbo.TCF14FI.CL_TARJETA AS CL_TARJETA,   
		       dbo.TCF11.COD_ESTABL AS COD_ESTABL,   
		       dbo.TCF04.DESCRIPCION AS ESTACION,    
		       dbo.TCF42.SALDO_PUNTOS AS SALDO_PUNTOS,   
		       dbo.TCF14FI.CL_CAMPA AS CL_CAMPA,   
		       dbo.TCF14FI.P_VENTA AS P_VENTA,    
		       dbo.TCF14FI.C_VENTA AS C_VENTA,   
		       dbo.TCF14FI.CL_EMPRESA AS CL_EMPRESA,   
		       CAST(dbo.TCF49.UNIDADES AS MONEY) AS UNIDADES,   
		       '' AS ArticuloM,   
		       dbo.TCF48.DARTI AS ArticuloC,   
		       dbo.TCF14FI.T_OPERACION AS T_OPERACION,   
		       0 AS IMPORTE,   
		       0 AS PUNTOSM,   
		       dbo.TCF14FI.SALDO_PREV AS SALDO_PREV,   
		       dbo.TCF14FI.SALDO_POST AS SALDO_POST,   
		       dbo.TCF49.PUNTOS AS PUNTOSC,   
		       CAST(ABS(dbo.TCF49.UNIDADES) AS MONEY) AS UNIDADESCANJE,   
		       '' AS CODPRODUCTO,   
		       dbo.TCF49.CL_REGALO AS CODREGALO    
		FROM dbo.TCF14FI INNER JOIN  
		     dbo.TCF49 ON dbo.TCF49.FECHA_MOV = dbo.TCF14FI.FECHA AND dbo.TCF49.HORA_MOV = dbo.TCF14FI.HORA AND   
		     dbo.TCF49.CL_EMPRESA = dbo.TCF14FI.CL_EMPRESA AND dbo.TCF49.CL_CENTRO = dbo.TCF14FI.C_VENTA AND    
		     dbo.TCF49.N_VENTA = dbo.TCF14FI.N_VENTA AND dbo.TCF49.CL_TPV = dbo.TCF14FI.P_VENTA     
		     INNER JOIN dbo.TCF48 ON dbo.TCF49.CL_REGALO = dbo.TCF48.CL_ARTI  
		     INNER JOIN dbo.TCF11 ON dbo.TCF14FI.CL_EMPRESA = dbo.TCF11.CL_EMPRESA AND dbo.TCF14FI.C_VENTA = dbo.TCF11.CL_CENTRO   
		     INNER JOIN dbo.TCF42 ON dbo.TCF14FI.ID_CUENTA = dbo.TCF42.ID_CUENTA   
		     INNER JOIN dbo.TCF04 ON dbo.TCF14FI.CL_EMPRESA = dbo.TCF04.CL_EMPRESA AND dbo.TCF14FI.C_VENTA = dbo.TCF04.CL_CENTRO     
		WHERE 
		      (dbo.TCF11.CL_CA = '000001')   
		      AND dbo.TCF14FI.C_RESULTADO = '000'   
              
		      AND (dbo.TCF14FI.T_OPERACION IN ('C','X') )  


GO