SELECT DISTINCT TCF14FI.FECHA, 
   TCF14FI.HORA, 
   TCF40.CL_CLIENTE, 
   TCF67.IMPORTE, 
   TCF14FI.CL_TARJETA, 
   TCF40.RAZON_SOCIAL, 
   TCF40.NOMBRE, 
   TCF40.APELLIDO1, 
   TCF40.APELLIDO2, 
   TCF40.EMAIL, 
   TCF40.SEXO, 
   EstacionesClubSmart_ACTIVAS.COD_ESTABL as ESTACION_CODIGO, 
   EstacionesClubSmart_ACTIVAS.DESCRIPCION as ESTACION_NOMBRE 
  FROM TCF14FI 
   INNER JOIN TCF67 ON TCF14FI.FECHA = TCF67.FECHA AND TCF14FI.N_VENTA = TCF67.N_VENTA AND TCF14FI.C_VENTA = TCF67.CL_CENTRO AND TCF14FI.CL_EMPRESA = TCF67.CL_EMPRESA AND TCF14FI.P_VENTA = TCF67.CL_TPV 
   INNER JOIN TCF48 ON TCF67.CL_ARTI = TCF48.CL_ARTI 
   INNER JOIN TCF40 ON TCF14FI.CL_CLIENTE = TCF40.CL_CLIENTE 
   INNER JOIN EstacionesClubSmart_ACTIVAS ON TCF67.CL_EMPRESA = EstacionesClubSmart_ACTIVAS.CL_EMPRESA AND TCF67.CL_CENTRO = EstacionesClubSmart_ACTIVAS.CL_CENTRO 
  WHERE (TCF67.CL_REGCAL NOT IN (29, 3)) 
   AND (TCF48.CL_ARTI IN ('121','122','124','127','130','133','421','422','427','430','433','434','480','481','482','483')) 
   AND (TCF14FI.T_OPERACION = 'M') 
   AND (TCF14FI.C_RESULTADO = '000') 
   AND (TCF14FI.E_OPERACION = 'R') 
   AND (UPPER(TCF40.EMAIL) <> 'JOSE.CARCELLER@IESE.NET') 
   AND (EstacionesClubSmart_ACTIVAS.BANDERA = 'SHELL') 
   AND (EstacionesClubSmart_ACTIVAS.COD_ESTABL <> '9999') 
  
  -- new
   AND (TCF14FI.FECHA >= convert(nvarchar(8),getdate()-7,112)) 
   and (TCF40.cl_cliente in (
       
        select distinct tcf40.CL_CLIENTE
        from [dbo].[TuOpinionImportaBajas]
        inner join CF_DISA.dbo.tcf40 on [TuOpinionImportaBajas].email = CF_DISA.dbo.tcf40.EMAIL
        where motivo is null
   ) 
   
   )
   --fin new
   
 AND (LEFT(TCF14FI.CL_TARJETA, 6) = '700421' OR LEFT(TCF14FI.CL_TARJETA, 9) = '972400077') 
 AND (TCF40.RAZON_SOCIAL IS NOT NULL AND TCF40.NOMBRE IS NOT NULL AND TCF40.APELLIDO1 IS NOT NULL AND TCF40.APELLIDO2 IS NOT NULL) 
   AND (TCF40.EMAIL IS NOT NULL AND LEN(TCF40.EMAIL)>0) 


ORDER BY TCF14FI.FECHA, TCF14FI.HORA