/* Migrar contratos PMTDR 2 -> 4 */


delete from PMTDR_V_4.dbo.ContratosDocumentos
delete from PMTDR_V_4.dbo.ContratosAsignacionComprobaciones
delete from PMTDR_V_4.dbo.Contratos

SET IDENTITY_INSERT PMTDR_V_4.dbo.Contratos ON;
GO
INSERT INTO PMTDR_V_4.[dbo].[Contratos]
           ([pkCodigo], [borrado]
           ,[cliente]
           ,[fkEstacionPkCodigo]
           ,[fkEstadoPkCodigo]
           ,[fkTipoPkCodigo]
           ,[nif]
           ,[numeroRegistro]
           ,[codigoSiras]
           ,[codigoSap]
           ,[ofertaComercial]
           ,[numeroTarjetas]
           ,[gasoleoProfesional]
           ,[diasDiferencia1]
           ,[diasDiferencia2]
           ,[fkContratoFueClientePkCodigo]
           ,[fechaFirmaComercial]
           ,[fechaFirmaContrato]
           ,[fechaSolicitudTarjetas]
           ,[fechaEntregaAltaEnSiras]
           ,[fechaRecepcionContrato]
           ,[fechaCreacion]
           ,[fechaUltimaModificacion]
           ,[fechaBorrado]
           ,[comentariosJefeZona]
           ,[comentariosDisa]
           ,[comentariosPrivados]
           ,[comentariosFueCliente]
           ,[numeroRegistroOriginal]
           ,[vendedorOriginal]
           ,[fkVendedorPkCodigo]
           ,[fkUsuarioCreacion]
           ,[fechaEnvioCanarias]
           ,[fechaEnvioMadrid]
           ,[descuentoInternacional]
           ,[descuentoNacional]
           ,[feeInternacionalSalePorDefecto]
           ,[feeNacional]
           ,[puestoFeeIntDejarBlanco]
           ,[segundaFacturaNacional]
           ,[cifEnAgenciaTributaria]
           ,[altaEso]
           ,[fdeNetInvoicing]
           ,[fechaAltaEnSAP]
           ,[contacto]
           ,[fechaEntradaDISA]
           ,[tlfFax]
           ,[cobroEnEuros]
           ,[direccion]
           ,[segundaFacturaInternacional]
           ,[esClienteInternacional]
           ,[fechaDestruccion]
           ,[fechaEnviadoComercial]
           ,[fechaPeticionDocumentacion]
           ,[soloCRTremitidoES]
           ,[codigoMandatoB2B])
SELECT [pkCodigo]
      ,[borrado]
      ,[cliente]
      ,[fkEstacionPkCodigo]
      ,[fkEstadoPkCodigo]
      ,[fkTipoPkCodigo]
      ,[nif]
      ,[numeroRegistro]
      ,[codigoSiras]
      ,[codigoSap]
      ,[ofertaComercial]
      ,[numeroTarjetas]
      ,[gasoleoProfesional]
      ,[diasDiferencia1]
      ,[diasDiferencia2]
      ,[fkContratoFueClientePkCodigo]
      ,[fechaFirmaComercial]
      ,[fechaFirmaContrato]
      ,[fechaSolicitudTarjetas]
      ,[fechaEntregaAltaEnSiras]
      ,[fechaRecepcionContrato]
      ,[fechaCreacion]
      ,[fechaUltimaModificacion]
      ,[fechaBorrado]
      ,[comentariosJefeZona]
      ,[comentariosDisa]
      ,[comentariosPrivados]
      ,[comentariosFueCliente]
      ,[numeroRegistroOriginal]
      ,[vendedorOriginal]
      ,[fkVendedorPkCodigo]
      ,[fkUsuarioCreacion]
      ,[fechaEnvioCanarias]
      ,[fechaEnvioMadrid]
      ,[descuentoInternacional]
      ,[descuentoNacional]
      ,[feeInternacionalSalePorDefecto]
      ,[feeNacional]
      ,[puestoFeeIntDejarBlanco]
      ,[segundaFacturaNacional]
      ,[cifEnAgenciaTributaria]
      ,[altaEso]
      ,[fdeNetInvoicing]
      ,[fechaAltaEnSAP]
      ,[contacto]
      ,[fechaEntradaDISA]
      ,[tlfFax]
      ,[cobroEnEuros]
      ,[direccion]
      ,[segundaFacturaInternacional]
      ,[esClienteInternacional]
      ,[fechaDestruccion]
      ,[fechaEnviadoComercial]
      ,[fechaPeticionDocumentacion]
      ,[soloCRTremitidoES]
      ,[codigoMandatoB2B]
  FROM [PMTDR_V_2].[dbo].[Contratos]
GO

SET IDENTITY_INSERT PMTDR_V_4.dbo.Contratos OFF;
GO


INSERT INTO [PMTDR_V_4].[dbo].[ContratosAsignacionComprobaciones]
           ([fkContratos_pkCodigo]
           ,[fkContratosComprobaciones_pkCodigo])
SELECT [fkContratos_pkCodigo]
      ,[fkContratosComprobaciones_pkCodigo]
  FROM [PMTDR_V_2].dbo.contratosAsignacionComprobaciones



SET IDENTITY_INSERT PMTDR_V_4.dbo.[ContratosDocumentos] ON;
GO
INSERT INTO [PMTDR_V_4].[dbo].[ContratosDocumentos]
           (pkcodigo, [borrado]
           ,[descripcion]
           ,[fkContratoPkCodigo]
           ,[fkTipoPkCodigo]
           ,[fkUsuarioPkCodigo]
           ,[nombreFichero]
           ,[tamano]
           ,[mimeType]
           ,[extension]
           ,[ruta]
           ,[directorio]
           ,[fechaCreacion]
           ,[fechaUltimaModificacion]
           ,[fkUsuarioUltimaModificacionPkCodigo]
           ,[fechaBorrado])
SELECT [pkCodigo]
      ,[borrado]
      ,[descripcion]
      ,[fkContratoPkCodigo]
      ,[fkTipoPkCodigo]
      ,[fkUsuarioPkCodigo]
      ,[nombreFichero]
      ,[tamano]
      ,[mimeType]
      ,[extension]
      ,[ruta]
      ,[directorio]
      ,[fechaCreacion]
      ,[fechaUltimaModificacion]
      ,[fkUsuarioUltimaModificacionPkCodigo]
      ,[fechaBorrado]
  FROM [PMTDR_V_2].dbo.[ContratosDocumentos]

  SET IDENTITY_INSERT PMTDR_V_4.dbo.[ContratosDocumentos] OFF;
GO
    
